### ISSUE TITLE
SonarCloud coverage not reporting for webapp

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1000]
SonarCloud is not getting data from Cypress, the coverage should be generated after each cypress run.
![image](https://github.com/bcgov/nr-spar/assets/25162561/2558214d-da03-4460-9f21-95acd4ba5d63)

**Comment by DerekRoberts** [comment]
@craigyu @RMCampos Happy number 1000!  :D :dancers: :fireworks: :beers: :partying_face:

**Comment by DerekRoberts** [comment]
@craigyu @RMCampos Looks like Cypress is working, but requires a file to be changed!  Junk PR below.  Please just close these if everything is good.
