### ISSUE TITLE
Remove ability to register A class registration in the legacy SPAR application

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1031]
**Describe the task**

Users with orchard manager access need to be blocked from registering A class seedlots in SPAR. Users with SPAR_SPR_NONMIN_FOREST_GENETICS will be able to see and use the A class registration form to update existing seedlot records (business area requirement).

The package files need to be updated to prevent users from entering A class seedlots

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by mgaseta** [comment]
To implement this, we would need to deal with WebADE, which is not what we want, so closing it as indefered.
