### ISSUE TITLE
update the agency selection input

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1038]
Add the functionality for a user to add their Acronym and pull in the correct client ID information. 

1) update FE to new component design, show success and error state
2) Complete testing across all screens
3) update client selection tool to add information when an option is selected

**Comment by craigyu** [comment]
Figma: https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=6665-77770&mode=design&t=IZE5blMjXxEBQnsF-4
