### ISSUE TITLE
Seedlot Reg Form Step 1 and 3 tests

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1040]
Implement Cypress tests for Step 1 Collection and Step 3 Interim Storage

Make a new Cypress spec file, name it `a-class-seedlot-reg-form.cy.ts`

Carefully analyze all the interactions can be possibly be done by a user then start implementing.
Make sure to test all possible scenarios, for example:
![Image](https://github.com/bcgov/nr-spar/assets/25162561/43ac5186-63c0-4bd8-ad57-638f556f1dfa)

For this input, the error message should be visible when the value is lower than 0, higher than 10,000 or having more than 3 decimal places.

Navigate between the steps by interacting with the progress bar
![Image](https://github.com/bcgov/nr-spar/assets/25162561/723e3962-a203-4722-9a82-c6d0bd86d2cc)

Tasks:
- [x] Test all inputs with valid and various invalid inputs
- [x] Test the functionality of the default agency and location code check box, unchecking it should make the fields empty, checking it should populate the fields with default agency and location code. Note that step 3's default is whatever is selected on step 1, so make sure to test this linkage; step 1's default is whatever user selected upon a seedlot creation.
- [x] isolate each test as much as possible. At minimum of 3 `it()` are needed for this task:
    1. test Step 1
    2. test Step 3
    3. test the linkage between Step 1 and 3

**Comment by RMCampos** [comment]
Rolled over to sprint 30 from 29.

**Comment by ngunner15** [comment]
- Seperate initial code into before() and beforeEach() block.
- Completed Step 1 test(without pop-up testing).

**Comment by ngunner15** [comment]
- Completed Step 3 test(without pop-up testing).

**Comment by ngunner15** [comment]
**Completed:**
- Step 1 popup test
- Step 3 popup test
- Step 1 and Step 3 linkage test

**Comment by RMCampos** [comment]
Very nice to see these comments! Good job @ngunner15
