### ISSUE TITLE
Spike dependency tables for seedlot ETL Tool batch update

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar#1049]
Identify and add dependent SEEDLOT tables to be included in the ETL tool mapping settings

**Comment by SLDonnelly** [comment]
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings

**Comment by RMCampos** [comment]
Duplicate of #1100

**Comment by SLDonnelly** [comment]
Where is this documented?

**Comment by marcionemec-daitan** [comment]
Hi @SLDonnelly , you can find the complete documentation here (including the Access requirement matrix table for ETL tool credential):

https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings
