### ISSUE TITLE
fetch spz by spu

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1083]
When a seedlot's status goes from `pending` -> `submitted`

The postgres backend should request a list of SPZs with the SPU from the primary orchard selected by the user. 

The oracle endpoint will then fetch a list of SPZs with the given SPU and send it back to postgres backend.

Postgress backend will insert rows to the `seedlot_seed_plan_zone` table with the results from oracle. 

For more details: [A-Class Area of Use SPZ](https://github.com/bcgov/nr-spar/wiki/A%E2%80%90Class-Area-of-Use-%E2%80%90-Seed-Plan-Zone)

- [ ] Area of use geo data
- [ ] SPZ list

**Comment by marcionemec-daitan** [comment]
Perfect! Looks correct to me!

**Comment by craigyu** [comment]
@marcionemec-daitan 
updated to use MIN instead as you suggested

**Comment by craigyu** [comment]
updated to a full stack ticket
