### ISSUE TITLE
SPIKE: research encryption in transit for the ETL tool

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1094]
**Describe the task**
Encryption in transit is needed for the ETL tool. A spike is needed to research options available. In the ETL planning meeting Paulo from Team Alliance shared this resource: https://paulushcgcj.github.io/articles/database-encryption-pt2

**Acceptance Criteria**
- [ ] research encryption in transit
- [ ] document pros and cons
- [ ] reach and document a decision as a team

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by marcionemec-daitan** [comment]
Following the Paulo's Article I would suggest to:

1) Create certification keys : 
`openssl req -x509 -nodes -newkey rsa:4096 -keyout server.key -out server.crt -days 365`

Please note this statement was used to test creating a cert pair files. For Production purpose it needs to be a more reliable certification file. 

2) Update Docker postgres database file to include the configuration to enable the SSL conection:
`FROM postgis/postgis:15-master

# Creates the directory for the certificates
RUN mkdir -p /certs/

COPY server.* /certs

RUN chmod 0600 /certs/server.*
RUN chown -R postgres:postgres /certs/server.*

# Set the pg_hba.conf file and add the permissions
RUN echo "hostnossl all all all reject" > /certs/pg_hba.conf
RUN echo "hostssl all all all scram-sha-256" >> /certs/pg_hba.conf
RUN echo "local all all scram-sha-256" >> /certs/pg_hba.conf
RUN echo "hostssl all all 127.0.0.1/32 scram-sha-256" >> /certs/pg_hba.conf
RUN echo "hostssl all all ::1/128 scram-sha-256" >> /certs/pg_hba.conf
RUN chown postgres:postgres /certs/pg_hba.conf
RUN chmod 0600 /certs/pg_hba.conf

# Copy the pg_hba.conf file to the container
RUN echo "cp /certs/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf" > /docker-entrypoint-initdb.d/01-pg_hba.sh
RUN chmod +x /docker-entrypoint-initdb.d/01-pg_hba.sh

# Reload the configuration
RUN echo "ALTER SYSTEM SET ssl = 'on';" > /docker-entrypoint-initdb.d/02-reload.sql
RUN echo "SELECT pg_reload_conf();" >> /docker-entrypoint-initdb.d/02-reload.sql

# Enable the pgcrypto extension
RUN echo "CREATE EXTENSION IF NOT EXISTS pgcrypto;" > /docker-entrypoint-initdb.d/03-pgcrypto.sql

# Copy the certificates to the container
RUN echo "cp /certs/server.crt /var/lib/postgresql/data/server.crt" > /docker-entrypoint-initdb.d/04-certificate.sh
RUN echo "cp /certs/server.key /var/lib/postgresql/data/server.key" >> /docker-entrypoint-initdb.d/04-certificate.sh
RUN echo "chown postgres:postgres /var/lib/postgresql/data/server.crt" >> /docker-entrypoint-initdb.d/04-certificate.sh
RUN echo "chown postgres:postgres /var/lib/postgresql/data/server.key" >> /docker-entrypoint-initdb.d/04-certificate.sh
RUN chmod +x /docker-entrypoint-initdb.d/04-certificate.sh

# Basic health check
HEALTHCHECK --interval=35s --timeout=4s CMD pg_isready -d db_prod

# Non-privileged user
USER postgres`

After that, all connections will be executed in a SSL protocol layer. 
pgcrypto extension will also be available to execute some manual encryption in column basis (need to decrypt it when reading).

**Comment by marcionemec-daitan** [comment]
Postgres database connection will need to include a parameter to define that connection will require a SSL protocol.

Code below is a example of implementation (Python + psycopg2): 

if database_config['type'] == 'POSTGRES':
            connection_string = 'postgresql+psycopg2://{}:{}@{}:{}/{}?sslmode={}'.format(
                database_config['username'], 
                database_config['password'], 
                database_config['host'], 
                database_config['port'],
                database_config['database'],
                'require')
