### ISSUE TITLE
Document backup process and the ETL tool and SPAR

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1097]
**Describe the task**
A spike needs to be done to understand back up and restore options for the ETL pipeline and for new SPAR.

Documentation of options needs to include an pros and cons

**Acceptance Criteria**
- [ ] Pros and cons of options listed
- [x] Documented in GH
- [ ] Discussed at a team collab session

- Needs #1268

**Comment by SLDonnelly** [comment]
rolled over from 32

**Comment by RMCampos** [comment]
@SLDonnelly Wiki page created: https://github.com/bcgov/nr-spar/wiki/SPAR-Backup-routine
