### ISSUE TITLE
Orable table list

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1099]
**Describe the task**
A list of tables needed for read/write proxy account access to the Oracle database. This list will be used to create a script to load the permissions needed for the ETL proxy account. This step is critical to complete to allow for needed testing of the ETL pipeline in the test and prod environment. 

**Acceptance Criteria**
- [ ] Generate list
- [ ] move on to ticket #, to create script for DBAs

**Additional context**
CC @webgismd

**Comment by RMCampos** [comment]
Rolled over to sprint 30 from 29.

**Comment by marcionemec-daitan** [comment]
You can find the complete documentation here (including the Access requirement matrix table for ETL tool credential):

https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings

I will be waiting for a review from the required stakeholders to start issue #1100

**Comment by marcionemec-daitan** [comment]
Adding xlsx file for validation (same was included in the https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings ):



[SPAR_Oracle_Table_Matrix_reference.xlsx](https://github.com/bcgov/nr-spar/files/15418395/SPAR_Oracle_Table_Matrix_reference.xlsx)
