### ISSUE TITLE
Legacy SPAR add hyperlink to new SPAR a-class reg screen

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1102]
Task:

The legacy SPAR application requires front end changes such that a user is blocked from entering or updating A class registration data in the old system. Instead, they will need to navigate to the new application to register A class seedlots. In previous planning meetings, it was determined that adding a "A class registration" section in the registration drop-down menu of legacy SPAR may be a bit difficult. An alternative is to add a hyper link to the new system on the home screen for users under the "additional links" section:

![Image](https://github.com/bcgov/nr-spar/assets/64149835/946eab71-0ec6-4744-97c6-1172a4ed037c)

The "email to Seed Info" option has a bug in which it sends the user to the SeedMap tool instead of emailing the SeedHelp email. While a link to the new SPAR application is being added to this section the PO would like to see the issue with the email link corrected such that when a user clicks on it, the default email service is opened and set up to send an email to: forhtip.seedhelp@gov.bc.ca

Acceptance criteria:

1. legacy SPAR code is updated to introduce the changes listed above
2. code changes are reviewed
3. changes are merged into test environment
4. changes are tested in test environment by PO

**Comment by RMCampos** [comment]
Rolled over from Sprint 30 to Sprint 31.

cc: @SLDonnelly @PMAKIA1
