### ISSUE TITLE
Improve Oracle execution time for bulk data

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar#1140]
**Describe the task**
The current time execution for Oracle data load is too high, taking hours to include/update more than 10k rows. 
Checking oracledb python library, we can use executemany instruction (https://python-oracledb.readthedocs.io/en/latest/user_guide/batch_statement.html) to gather better times. 

**Acceptance Criteria**
- [ ] Execute unit tests
- [ ] Time execution for 10k rows less than 5 minutes
- [ ] Update ETL Documentation

**Additional context**
- Valid only in data upsert in Oracle database.

**Comment by kevinginley** [comment]
Rollover to Sprint 30

**Comment by marcionemec-daitan** [comment]
As we are starting to gather data from Oracle to update Postgres database, this task can be handled in next sprint. 
Please, let me know if you will need any assistance to do this task, maybe large updates on Oracle database will not be so slow when using the SPAR openshift environment, it would need some tests!

**Comment by RMCampos** [comment]
Should we discuss this one with @ronrobb, @SLDonnelly ?

**Comment by mgaseta** [comment]
Agreed with @RMCampos and @SLDonnelly this can be closed.
