### ISSUE TITLE
Ownership Cypress Test

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1141]
1. Interact with the step 2 ownership of the A Class Registration form and come up with a test plan that tests all the functionalities of the form. Add the test plan as a comment in this issue. 
2. Implement tests according to the test plan.

Should test with at least 3 owner agencies

Use the same seedlot number for this test as the one from step 1 & 3's test

Definition of done:
- [x] Test plan created
- [x] Test implemented

**Comment by craigyu** [comment]
Increased story point from 2 -> 3 due to the complexity of the page

**Comment by ngunner15** [comment]
**Test Case Steps**

1. User can go to Ownership(Step 2) seedlot registration form by clicking `Next` button on Step 1.
2. Create a fixture to store static values like headings, subtitles etc.
3. User can see correct information on Ownership(heading, subtitle).
4. User can hide owner agency section by clicking on the up arrow button.
5. The owner agency section has the same title as the `Owner agency` and the subtitle is the same as `Owner portion(%)` which is 100% by default.
6. User can uncheck the checkbox and change the `Owner agency` and `Owner location code`.
7. User can change `Reserved (%)` and `Surplus (%)`.
8. User can enter `Owner agency` by clicking `open the client search` modal.
9. User can enter `Funding source` and `Method of payment` from the dropdown menu.
10. User can click on `Add owner` button and a new owner agency section is added to the page.
11. User can delete the owner agency section by clicking `Delete owner` button.
12. User can change the `Owner portion(%)` the new owner agency section.
13. User can click on `Next` button.


**Test Case Expected Results**

Step 3:
Create a test that imports fixture to check the title and subtitle.

Step 6:
Check for error msg when it is invalid `Owner agency` and `Owner location code`.

After Step 7:
The total of `Reserved (%)` and `Surplus (%)` should be equal to `Owner portion(%)` 

After Step 8:
Check the `Owner agency` and `Owner location code` are the same in the owner agency section as the one selected in `open the client search` modal.

Step 12:
Check for error msg if both the owner agency section should be more than 100% or less than 100%.

After Step 13:
User is on Interim storage step and the SVG on Step 2 with right tick is visible(that means completed).

**Comment by ngunner15** [comment]
Added all the tests.
