### ISSUE TITLE
Orchard Step Cypress Test

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1142]
Test Step 4 - Orchard with Cypress
Add a new spec: `../a-class-seedlot-reg-form-orchard.cy.ts`

## Information

An orchard has a set of parent trees, e.g. 
- orchard 109 has parent tress [1, 3, 5, 7, 9]
- orchard 110 has parent trees [2, 3, 5, 4, 6, 8, 10]

A user can select up to 2 orchards

If one chard is selected in Orchard step, for example orchard 109, step 5 should display parent tree [1, 3, 5, 7, 9]. 

If two orchards are selected, the union of the two orchards parent trees should be displayed in step 5

For example, a user selects orchard 109 and orchard 110
On step 5, the displayed parents are [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## Test parent tree union

select ORCHARD_A only
37
69
101 
129 
192

select ORCHARD_B only
37 
38  
53
54 
60

UNION ORCHARD_A AND ORCHARD B 
Get a set of parent tree numbers SET X = [37, 38, 53, 54, 60, 69, 129, 192] 

Select ORCHARD_A and ORCHARD_B
find the first  `X.length()` number of rows' parent numbers

Compare if the two sets are the same

## Other testing

Test the remaining inputs

**Comment by ngunner15** [comment]
**Completed**

- Title and subtitle test
- All input tests

**Comment by ngunner15** [comment]
Added validation test

**Comment by SLDonnelly** [comment]
Draft pull request in place so that debugging can occur. There is an issue with saving @craigyu @ngunner15

**Comment by ngunner15** [comment]
Fixed the issue on dev collab, thanks @craigyu

**Comment by ngunner15** [comment]
Tests passing on local environment, but failing in GitHub Actions

**Comment by craigyu** [comment]
rolled over from 31 to 32

**Comment by SLDonnelly** [comment]
RO from 32
