### ISSUE TITLE
ETL Historical data from Oracle to Postgres (Non-domain tables)

### ISSUE THREAD

**Issue by marcionemec-daitan** [bcgov/nr-spar#1144]
**Describe the task**
Provide the tables listed in https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Dataset+mappings to be mapped for Data synchronization between Oracle and Postgres

**Acceptance Criteria**
- [x] Tables configured to synchronize one way (ORCL -> PG)
- [ ] Deployment in Main repository and in the Spar's Dev environment to allow integration tests.
- [x] Unit tests for each process

**Additional context**
- All related to Spar's ETL Tool feature

**Comment by marcionemec-daitan** [comment]
Tables already included in the branch:

1. spar.smp_mix
2. spar.smp_mix_gen_qlty
3. spar.seedlot_parent_tree
4. spar.seedlot_parent_tree_smp_mix
5. spar.seedlot_genetic_worth
6. spar.seedlot
7. spar.seedlot_orchard

Note: for spar.seedlot_orchard, is needed to update the unique key constraint to:
`CONSTRAINT unique_seedlot_orchard_key UNIQUE (seedlot_number, orchard_id, primary_ind)`

Currently it is: 
`CONSTRAINT unique_seedlot_orchard_key UNIQUE (seedlot_number, orchard_id)`

Suggested DDL change: 
`alter table spar.seedlot_orchard drop CONSTRAINT unique_seedlot_orchard_key;
alter table spar.seedlot_orchard add  CONSTRAINT unique_seedlot_orchard_key UNIQUE (seedlot_number, orchard_id,primary_ind);`

**Comment by ronrobb** [comment]
Hi, @marcionemec-daitan. The SEEDLOT_ORCHARD UK looks correct to me as-is.  Why are you suggesting a change?  An Orchard cannot be primary and non-primary for a Seedlot, I am assuming.  @craigyu Can you confirm or ask, Sabina?

**Comment by marcionemec-daitan** [comment]
Hi @ronrobb , Thank you for your comment and Nice to meet you! 

You're right, I was getting a duplicate PK error while bringing data from Oracle to Postgres, but it was caused because previously data gathered doesn't had the primary_ind catched, so, it was stored with default value false. When extracting data from a Secondary_orchard_id from seedlot, the error was raised. 
So, I cleaning the data and tried again and it works, so, no need to change the UK, as it looks correct. 

Thank you for your review. By the way could you please review the issue #1100  and #1099 , regarding tables to be synchronized between Oracle and Postgres?

**Comment by marcionemec-daitan** [comment]
My thoughts/ observations regarding the data movement processes from Oracle to Postgres:
 
**For SMP_MIX_GEN_QLTY table:**
Column entry_userid and update_userid don't exist in Postgres but not in Oracle, and in Postgres it is non-nullable:
 
Proposed solution:
Bring columns from Oracle as 'Legacy SPAR'
 
**For SMP_MIX:**

1) Column entry_userid and update_userid don't exist in Postgres but not in Oracle, and in Postgres it is non-nullable:
 
Proposed solution:
Bring columns from Oracle as 'Legacy SPAR'
 
2) proportion column does not exists in Oracle database.
 
Proposed solution:
Calculate proportion based on amount_of_material column and parent_tree_id from seedlot table
 

**For SEEDLOT_PARENT_TREE_SMP_MIX:**

1) Table structure is very similar to SMP_MIX_GEN_QLTY (just one column exists on one table and not exists in another), so, the source is the same? Considering yes.
 
 
**For SEEDLOT_ORCHARD:**

1) Only non-audit columns is SEEDLOT_NUMBER and ORCHARD_ID. Those data exists on Oracle SEEDLOT table, but also exists another column, SECONDARY_ORCHARD_ID. 
   Does this data should included in the gathering process?
 
Default: Including only SEEDLOT_NUMBER And ORCHARD_ID data. SECONDARY_ORCHARD_ID is considered as primary_ind = False.
 

**For SEEDLOT_GENETIC_WORTH :**

1) What is the scope of this table? Table in Oracle doesn't have the tested_parent_tree_id but have the parent_tree_id and estimated_ind columns.
2) How to obtain or calculate tested_parent_tree_cont_pct as this column doesn't exist in tables in Oracle?  
 
Default: tested_parent_tree_cont_pct is gathered as zero, only to be a placeholder while we define how to gather this column value.
 
 
**For SEEDLOT_SMP_MIX :**

1) What is the scope of this table? Mapped table in Oracle (SMP_MIX_GEN_QLTY) have different grain (parent_tree_id x seedlot_number). 
 
CC: @craigyu , @RMCampos

**Comment by marcionemec-daitan** [comment]
Another question is regarding ACTIVE_ORCHARD_SPU table:

Table has the following structure:
orchard_id varchar(3) NOT NULL,
seed_plan_unit_id int4 NOT NULL,
active_ind bool NOT NULL,
retired_ind bool NOT NULL,
no_spu_ind bool NOT NULL,

What I didn't identified anything similar on Oracle Database. So, do you know what is the source for this table? 

CC: @craigyu , @RMCampos , @SLDonnelly

**Comment by ronrobb** [comment]
I haven’t been able to access the oracle database yet so it’s hard to answer these questions.  @Donnelly, Sabina ***@***.***> ?
________________________________
