### ISSUE TITLE
Vanity URLs

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1174]
Set up vanity URLs for test and prod environment.

The two URLs have been created:
- PROD https://spar.nrs.gov.bc.ca/
- TEST https://spar-tst.nrs.gov.bc.ca/

Jira tickets
- [SSL Certificates required for new vanity URL for SPAR](https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-22684)
- [New vanity URL for spar.nrs.gov.bc.ca needed](https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-22683)

Example from FOM
https://github.com/bcgov/nr-fom/issues/608

**Comment by DerekRoberts** [comment]
CSRs have been provided and I have updated install scripts to test out.  Until somebody gets back to us with certs (base and ca/L1k) this is going into the waiting pile.

JIRA
https://apps.nrs.gov.bc.ca/int/jira/browse/INFRA-22684

**Comment by DerekRoberts** [comment]
Done!
