### ISSUE TITLE
feat: PR triggers

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#1191]
At some point during our revisions PR deploy triggers were dropped.  Restore them, so non-code changes won't trigger builds and deploys.

New request: only deploy fluentbit when log_env_target is provided.

**Comment by RMCampos** [comment]
Ideally, we could have something like this, for each component:

**PR Open - DEV**
- If Changes ➡️ then, triggers both `build` and `deploy`
- If no changes  ➡️ then, skip `build`, deploying latest tagged `test` image

**PR Closed - Success Merge**
- If Changes ➡️ then, triggers both `build` and `deployments`
- If no changes  ➡️ then, skip everything on this component, both `build` and `deploy`

**Comment by DerekRoberts** [comment]
@RMCampos That's workable!  Are we treating Oracle-API any differently?  I think everything else makes sense to build and deploy as a group.

**Comment by RMCampos** [comment]
@DerekRoberts I'd say to treat Oracle-API the same way.
