### ISSUE TITLE
CONSEP wireframes: Germination count screens

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#1195]
**Acceptance Criteria**
- [ ] Create wireframes in Mural for germination count screens: Germination test result, abnormals, germination rank, test history, daily germination graph

**SME/User Contact**
Victoria Lei

**Comment by PMAKIA1** [comment]
Hey @kevinginley is this ticket a roll over from Sprint 30?

**Comment by kevinginley** [comment]
@PMAKIA1 Nope, this ticket is brand new for Sprint 31

**Comment by craigyu** [comment]
rolled over from 31 to 32
