### ISSUE TITLE
Extraction and Storage Cypress Test

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1245]
Implement a Cypress test for the final step of the A-Class registration form.

Name the test file in accordance with the other files

**Comment by ngunner15** [comment]
**Completed**

-  title and subtitle test
-  edit agency test
-  date test
-  added fixture data

**Comment by ngunner15** [comment]
Cypress Test fails in GitHub Action, but passes locally

**Comment by craigyu** [comment]
rolled over from 31 to 32
