### ISSUE TITLE
[Bug] Read-only combo box is interactive

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1258]
Interacting with a read-only combo box can make the selected empty. The data (`selectedItem`) is changed on the front end, however the source data is not impacted. The expected action is that users cannot interact with comboboxes etc when in read only mode

![Image](https://github.com/bcgov/nr-spar/assets/25162561/200da360-b36b-4563-b87a-a01377f8062e)

**Comment by mgaseta** [comment]
Adding this to blocked, couldn't reproduce the issue...

**Comment by RMCampos** [comment]
Not able to reproduce it here too.

**Comment by SLDonnelly** [comment]
we can't reproduce so this ticket can be closed
