### ISSUE TITLE
⏫  Enable regular Backups for postgres data

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#1268]
## User Story
As a user, I want to have a routine in place for backing up all the postgres database.

## Acceptance Criteria
- Backup strategy defined
- Document everything (issue #1097)

## UPDATE!
This is the recommended solution.
https://github.com/bcgov/nr-compliance-enforcement/wiki/Database-Backups

- S3 upload will be handled in a separate issue: #1670

**Comment by DerekRoberts** [comment]
Some existing work in the QuickStart repo.  Buckets for SPAR have already been purchased.
https://github.com/bcgov/quickstart-openshift/issues/2000

**Comment by DerekRoberts** [comment]
Recommended solution here.  Implementing - hopefully successfully! - this week.
https://github.com/bcgov/nr-compliance-enforcement/wiki/Database-Backups

**Comment by RMCampos** [comment]
## Issues found

- The [backup-container](https://github.com/bcgov/backup-container) repository it's not updated with latest **Kubernetes** changes. It's still including `DeploymentConfig` instead of `Deployment`. Here for more: [DeploymentConfig API is being deprecated in Red Hat OpenShift Container Platform 4.14](https://access.redhat.com/articles/7041372) and [Replace deprecated DeploymentConfigs with deployments](https://developers.redhat.com/learn/openshift/replace-deprecated-deploymentconfigs-deployments)
  - In order of contributing with the government tech community, we provided a PR with updates, here: https://github.com/bcgov/backup-container/pull/3
