### ISSUE TITLE
Document CORS best practices and recent changes

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#1271]
## User Story
As a user, I want to have a good wiki page covering all the details regarding CORS and its implementation on SPAR.

## Acceptance Criteria
- Wiki page written and saved on SPAR Wiki
- Reviewed by Sabina or other teammember

**Comment by SLDonnelly** [comment]
RO from 32

**Comment by RMCampos** [comment]
Page can be found here: https://github.com/bcgov/nr-spar/wiki/CORS-Best-Practices

**Comment by mgaseta** [comment]
Looking good! Nice job @RMCampos!
Approved from my side!

**Comment by RMCampos** [comment]
Reviewed and approved by @SLDonnelly.
