### ISSUE TITLE
SPAR Testing

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1272]
**Describe the task**
Assist with SPAR testing

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by kevinginley** [comment]
Register an a-class seedlot:

![Image](https://github.com/user-attachments/assets/a6cdd570-9f3d-4dd4-afe0-90613d8deea6)

I would remove the subheading "Register a new A-class seedlot" (redundant with heading above)

**Comment by kevinginley** [comment]
A-class seedlot created:



![Image](https://github.com/user-attachments/assets/bff96fd6-04de-4794-ac09-7f9018cd5755)

Change "Seedlot's main screen" to:
"Seedlots main screen"
(removing apostrophe)

**Comment by kevinginley** [comment]
Client search modal:



![Image](https://github.com/user-attachments/assets/5357aa40-bb45-4e0e-a33c-a3f1a313fcd7)

"To view more information about the client, you can go to client search screen."

change to:

"To view more information about the client, go to the client search screen."

**Comment by kevinginley** [comment]
Collection methods:



![Image](https://github.com/user-attachments/assets/346579b5-55eb-4590-a880-977ae2b652a9)

Would it make sense to list the collection methods in alphabetical order?

**Comment by kevinginley** [comment]
Cone and pollen count:



![Image](https://github.com/user-attachments/assets/f7279894-f585-4652-b9b0-bccf8cfdc72a)

"Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"
I would change it to:
"Enter the cone and pollen count estimate for the orchard's seedlot"


SMP success on parent:



![Image](https://github.com/user-attachments/assets/343be4c0-e624-48b6-818e-3ef1e75052e5)

"Enter the same SMP success on parent or Non-orchard pollent contaminant to all parent trees"

I would change "Non-orchard" to "non-orchard"


Calculation of SMP mix:



![Image](https://github.com/user-attachments/assets/71701239-6c9d-445c-93ea-5836c3d6fff3)

"Enter the estimative of SMP success for the orchard's seedlot"
I would change to:
"Enter the SMP success estimate for the orchard's seedlot"

**Comment by kevinginley** [comment]
File upload:



![Image](https://github.com/user-attachments/assets/b0e6b4a1-32a7-488c-8b0c-d92e395658fd)

"Note: When uploading a file all previously filled data within the table will be replaced." 
Please change to:
"Note: When uploading a file, all previously filled data in the table will be replaced."

**Comment by kevinginley** [comment]
Breeding value of SMP mix used
![Image](https://github.com/user-attachments/assets/600f4d9b-5aa1-4ebe-ac05-277c66e22a2c)

The subheading is redundant here in my opinion. I would remove that and update the heading to read:

"Breeding value of SMP mix used on parent"

**Comment by kevinginley** [comment]
![Image](https://github.com/user-attachments/assets/fb3cd27d-d28f-4188-addf-1abd3e87f3f8)
"SMP Mix geospatial summary"
Please change to:
"SMP mix geospatial summary"

**Comment by kevinginley** [comment]
Step 6:

![Image](https://github.com/user-attachments/assets/65807895-f6f1-4159-b21d-94427a5da4c1)
"Enter the extractory agency information and extraction's star and end dates for this seedlot"
change to:
"Enter the extractory agency information and extraction's start and end dates for this seedlot"
(change "star" to "start")


![Image](https://github.com/user-attachments/assets/137bd61f-8615-42cb-9148-359199578b93)
"Enter the seed storage agency information and storage's star and end dates for this seedlot"
change to:
"Enter the seed storage agency information and storage's start and end dates for this seedlot"
(change "star" to "start")

**Comment by kevinginley** [comment]
![Image](https://github.com/user-attachments/assets/ca677292-d324-4e3c-a634-554fb6bf50ef)

This one's a bit tricky, but in Canada we use the French spelling of center, so it should actually be "Tree Seed Centre" instead of "Tree Seed Center"

When Tree Seed Centre comes up in data queries, it is spelled the French way in the database, so it would be nice to keep consistent.

Hopefully this is more of a find-and-replace kind of function in the front-end

**Comment by kevinginley** [comment]
Declaration modal:

![Image](https://github.com/user-attachments/assets/6cd77c8a-2a63-4e89-acdd-d6cfede8d4db)

Declaration:
"Please, be sure to review the content and check if everything is correct with your seedlot registration.
Go to first step and review the form."

Please change to:
"Please review this form to ensure the information is correct for this seedlot registration.
Click here to go back to the first step."


And then have "Click here" link to the first step in the form

**Comment by mgaseta** [comment]
Done on task #1421, closing this one.
