### ISSUE TITLE
Bring in additional testers to do their jobs in old SPAR (test env)

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1276]
**Describe the task**
Changes have been made to old SPAR to turn off the A class registration screen, correct the email hyperlink and to add in a secret button to open old A class registration screens.

We need additional testers from the business area to ensure that other workflows and screens have not been inadvertently impacted by these changes. A test plan will be created and sent out to testers.

**Acceptance Criteria**
- [ ] create test plan
- [ ] line up testers and get them to fill out test plan
- [ ] compile feedback and write up any tickets for bugs

**Comment by mgaseta** [comment]
Closing it, since it's in the done column.
