### ISSUE TITLE
Michelle, Sabina, Derek, Craig discuss database backup plan

### ISSUE THREAD

**Issue by PMAKIA1** [bcgov/nr-spar#1283]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by DerekRoberts** [comment]
We decided on: "yes, do backups."  There'll be a bunch of follow-up issues.
