### ISSUE TITLE
Team identify what to back up (Postgres only), how often to backup, how will test back up

### ISSUE THREAD

**Issue by PMAKIA1** [bcgov/nr-spar#1284]
**Describe the task**
A clear and concise description of what the task is.

**Acceptance Criteria**
- [ ] first
- [ ] second
- [ ] third

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by craigyu** [comment]
What: entire DB
Frequency: Twice a day (noon and midnight)
Where: S3 Buckets
