### ISSUE TITLE
decision: scaling

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#1288]
We're currently deploying one container for each component in PR, TEST and PROD.  Is that actually enough for PROD?  Discuss and resolve!

**Comment by RMCampos** [comment]
@SLDonnelly I think it worth a quick call to discuss this issue. 
@DerekRoberts could you join one of your Dev Collab sessions at 11 am?

I'd say one it's not enough, unless it is. It really depends on the usage. We could be working with ASG (auto-scaling groups) based on a metric, such as CPU or Memory. Now we have SysDig that can help understand usages.

**Comment by DerekRoberts** [comment]
@RMCampos Sure! Please send details and I'll attend.
