### ISSUE TITLE
Revision_count mismatch and version reconcilation

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1300]
**Describe the task**
UI needs to be updated to alert users when 2 or more people are editing the same form. The user to save first, becomes the source of truth and the second user needs to be notified that they are not using the most up to date data and need to reload. The second users needs to be prevented from over-riding the changes of the 1st by accident.

![Image](https://github.com/bcgov/nr-spar/assets/64149835/ff060fe9-f9da-4700-975b-27f415fea780)

**Acceptance Criteria**
- [ ] what is required for this task to be complete?
- what is the finishing point or end state of this task?
- [ ] what is the output of this task?

**SME/User Contact**
(may want to use a persona to fill this in)

**Additional context**
- any additional details that could not be captured above

**Comment by mmarsoleta** [comment]
file at: [Figma](https://www.figma.com/design/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?node-id=8125-10707&t=MP1NkZssRI3JJ9bA-4)
