### ISSUE TITLE
🏆 update smart save functionality to handle multiple users editing the same form

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1301]
**Describe the task**

Currently we are using the seedlot as the key for the smart save, but this needs to be enhanced to account for multiple users updating the same seedlot at once. 

Before user saves the form, the FE needs to refer to the userID plus the seedlot number to be used as a key when saving seedlot progress. 

At this point, we don't believe that we need to update the endpoint, but instead we can use the userid and seedlot number as unique combination in a string on the FE.  

***We need to make sure that any updates in the seedlot table happen with the addition of the revision_count in the where clause. 

**Acceptance Criteria**
- [ ] smart save working for two or more different users editing at the same time
- [ ] tested and merged

**Additional context**

This ticket is related to #1300 

![Image](https://github.com/bcgov/nr-spar/assets/64149835/ff19f79a-2461-4e6a-ad8f-fb29c66965fa)

**Comment by craigyu** [comment]
https://github.com/bcgov/nr-spar/issues/1300#issuecomment-2206886051
