### ISSUE TITLE
Looking at deployments issues

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#1305]
Wrong deployment number (tag) on TEST and PROD!

![Image](https://github.com/bcgov/nr-spar/assets/2219519/82461926-35f7-4028-82c5-b51137234208)

**Comment by DerekRoberts** [comment]
@RMCampos We don't replace the database on TEST or PROD!  There's an `overwrite: true` parameter for deployment.  We can still deploy manually or delete and re-run.
