### ISSUE TITLE
logical lock for the_SEEDLOT

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1308]
**Describe the task**
When updating SEEDLOT related data (i,e. child tables such a parent trees) it is a good idea to logically lock the SEEDLOT.  For example, if two users are editing parent tree contribution and are unaware of one another, both could save their data (because the code is only looking at revision count on the parent tree records).  The parent tree contribution could become a mess if that occurs. To prevent such issues it is typical to "touch" the seedlot record after all parent trees are updated.  If the touch succeeds then commit everything and if it fails (0 rows updated) then rollback everything.
 
The touch is just
 
UPDATE seedlot
  SET update_userid = :user
    , update_timestamp = SYSTIMESTAMP
   , revision_count = revision_count + 1
WHERE seedlot_number = :lot_number
   AND revision_count = :revision_count_selected;

CC @ronrobb 

**Acceptance Criteria**
- [ ] tested by developer 
- [ ] merged

**Comment by SLDonnelly** [comment]
RO from 32

**Comment by RMCampos** [comment]
Notes:
- Non TSC Admin users cannot edit/update a seedlot (or its child tables). The main Seedlot table is firstly touched when the user starts the Seedlot registration, in the **Create A-class seedlot** page, after clicking the **Create seedlot number** button. After that, no updates or child tables insert will happen until the user finishes the registration and submits the complete form.
- After submission (with SUB status), users cannot update or touch the seedlot details.
- After submission (with SUB status), only TSC Admin users can edit (update) the seedlot record and its child tables, through the Review Form. The regular form allows only read, no changes, even for TSC Admins.
- When a TSC Admin is editing the review form, if he saves (not approving or disapproving, only saving), the seedlot table gets updated for some Hibernate readon. **I'm working on it, to understand why and disable this feature**
