### ISSUE TITLE
UX improvement: 404 error screen

### ISSUE THREAD

**Issue by mmarsoleta** [bcgov/nr-spar#1323]
**Describe the task**
Design an user-friendly 404 error page to enhance user experience across our platform

**Acceptance Criteria**
- deliver a reviewed and validated version of 404 error screen to development

**SME/User Contact**
- Devs
- PO
- FDS 

**Additional context**
The task involves creating a custom 404 screen that aligns with our brand identity and provides clear guidance to users who encounter a page not found error. The design should incorporate intuitive navigation options and engaging visuals to mitigate user frustration and encourage exploration of other content.

Figma file: [Figma file](https://www.figma.com/design/XpF15ggH9Gn7FeXa9zTNYm/SPAR---404-and-403-errors?m=auto&t=0ZzLzgVcqiqcrmoL-6)

**Comment by mmarsoleta** [comment]
Suggestion:

Error 404 Page (Page Not Found)
Visual Concept: A cone or seed in a forest setting, appearing lost.
Suggested Text: "Oops! It looks like this page got lost in the forest."
Graphic Elements: Illustration of a cone or seed with a confused expression or looking for a path, surrounded by trees and plants.
Action Button: "Back to Home" or "Search bar”

**Comment by kevinginley** [comment]
@mmarsoleta @SLDonnelly,

Below is the illustration so far for the 404 error screen. All the colours used are from the design system. I tried to keep with the blue theme for the background while reserving a warmer colour for Coney the cone.

![Image](https://github.com/user-attachments/assets/70aeefb7-b13c-4af3-8653-bbd9b08f8173)

Please let me know what you think and if there's anything you'd like to change. Once we're happy with it, I will make the dark mode version and implement them in the corresponding screens in Figma.
