### ISSUE TITLE
UX improvement: 403 forbidden

### ISSUE THREAD

**Issue by mmarsoleta** [bcgov/nr-spar#1324]
**Describe the task**
Design a informative 403 Forbidden error page to enhance user understanding and navigation experience across our platform. e.g. User doesn't have access to a seedlot number

**Acceptance Criteria**
- Deliver a review and validated screen to development

**SME/User Contact**
- PO
- Devs
- FDS

**Additional context**
- The task involves creating a custom 403 screen that adheres to our brand identity and effectively communicates the access restriction to users. The design should prioritize clarity and provide actionable steps for users to resolve the issue or seek assistance.

Figma file: [Figma file](https://www.figma.com/design/XpF15ggH9Gn7FeXa9zTNYm/SPAR---404-and-403-errors?m=auto&t=0ZzLzgVcqiqcrmoL-6)

**Comment by mmarsoleta** [comment]
Error 403 Page (Access Denied)
Visual Concept: A cone or seed acting as a security guard, perhaps with a whistle or barrier.
Suggested Text: "Access Denied! This cone is protecting this area."
Graphic Elements: Illustration of a cone or seed with a guard or security look, maybe with a small fence or "Access Restricted" sign.
Action Button: "Back to Home" or "Contact Support"

**Comment by kevinginley** [comment]
@mmarsoleta @SLDonnelly,

Below is the illustration so far for the 403 error screen. All the colours used are from the design system. I tried to keep with the blue theme for the background while reserving a warmer colour for Coney the cone.

![Image](https://github.com/user-attachments/assets/fd02bea7-519f-4a04-a478-e08c5510cdf5)

Please let me know what you think and if there's anything you'd like to change. Once we're happy with it, I will make the dark mode version and implement them in the corresponding screens in Figma.

**Comment by kevinginley** [comment]
Figma file can be found here:
https://www.figma.com/design/lawhavsjilWS7f8anaGf0a/Testing-list?node-id=192-99950&t=iHGdivQEIOPNcf3d-1

The image .svg can be found here:
![Image](https://github.com/user-attachments/assets/8c7b8137-d69e-47c1-b394-75d64ecb48e3)
