### ISSUE TITLE
Acronym display bug

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1345]
the agency acronym input display different text when in different mode, this bug might appears in other screens as well.

![Image](https://github.com/bcgov/nr-spar/assets/25162561/14f80bab-09c5-4907-9463-1b0b793c0c4c)

**Comment by mgaseta** [comment]
Few questions for @SLDonnelly:
- When in read mode, should we display only the acronym or the whole name (client number - name - acronym)?
- Which is the correct pattern for the agency field label? Should it say only: "XXX agency", "XXX agency acronym"
- For the location code field, should the label of the field display "agency location code" or "applicant agency number"?
- The email field label, should it be "Email address" or "Applicant email address"?

**Comment by SLDonnelly** [comment]
@mgaseta 

-     When in read mode, should we display only the acronym or the whole name (client number - name - acronym)?
This is a good question, I think it's nice having all the information visible. @mmarsoleta @kevinginley do you agree?

-     Which is the correct pattern for the agency field label? Should it say only: "XXX agency", "XXX agency acronym"
  "XXX agency acronym"
-     For the location code field, should the label of the field display "agency location code" or "applicant agency number"?
      "agency location code"
-     The email field label, should it be "Email address" or "Applicant email address"?
I think that just "email address" is fine

**Comment by kevinginley** [comment]
Yes I agree with having (client number - name - acronym) all be visible in read mode
