### ISSUE TITLE
Add Cancel button at seedlot review page and Client + Code Refactor

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1361]
Issue:

Need to add a cancel button at the seedlot review page to go back to read mode without saving the data.

Task:

Michelly/Kevin to determine the position and design of the button
Craig to implement, test and merge

From Michelly: 

Also, we have a few scenarios of leaving without saving in here if necessary:

https://www.figma.com/design/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?node-id=5816-108475&t=1mm4TyowleOskYbL-4

Screenshot 2024-07-12 at 11 28 47

![Image](https://github.com/user-attachments/assets/c01a2d2f-28ef-497e-8b89-ac933f3e2a4d)

fix the problem where multiple owners can all have 100% ownership

**Comment by craigyu** [comment]
rolled over from 32 to 33

**Comment by mmarsoleta** [comment]
Instead of "Cancel", could the button's label be something like "Back to review" - It sounds more intuitive i guess... 
What do you say @kevinginley ?

**Comment by kevinginley** [comment]
I agree, I like "Back to review"

**Comment by craigyu** [comment]
upped to 3 for refactoring
