### ISSUE TITLE
Seedlot registration form FE changes

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1386]
1) In the seedlot registration form, the screen sometimes defaults to the middle of the screen and cuts off the header. The default when a user switches between screens should be that it starts at the top.

2) On screen 5, there is a blue box that appears on the column headers. Currently, this box/indicated interaction does nothing but it would be good to turn the headers into sortable columns

![Image](https://github.com/user-attachments/assets/b97d9ae1-e45f-4360-a16b-6acdc3aa097d)

3) on the seedlot registration forms, the seedlot number is small. Make it bigger and in line with the header?

4) the tabbing between the agency acronym and the location code needs to be fixed (currently it pops down to the client search)

5) when the user selects yes for pollen contamination, the wording needs to be changed to "contaminant pollen breeding value"

![Image](https://github.com/user-attachments/assets/0fc9ad42-456d-48d0-b396-c6db58aa80c5)

6. Warning for when a user is going to navigate without saving (see Michelly's comment below)

**Comment by mmarsoleta** [comment]
4: We already have a design for that, I've been using the number with the title for a while now, the change was inside the adjustments for seedlot registration ticket (https://github.com/bcgov/nr-spar/issues/827) 

![Screenshot 2024-07-12 at 08 59 07](https://github.com/user-attachments/assets/d1a0b2aa-f7eb-4af9-bc2d-52001b1a7403)

**Comment by mmarsoleta** [comment]
2. I believe the icons's sizes are all fixed to 16px in the DS. Increasing just the "+" would make it inconsistency with the rest of them. Maybe another alternative would be adding the labels together with the icons - to increase its visibility. 

![image](https://github.com/user-attachments/assets/a2bbf02c-3fce-4386-bf17-e26ddbde8aa9)

**Comment by mmarsoleta** [comment]
5. Would the tab/focus order works better if the location code was enabled or this would cause the interaction to be more complex in terms of validation? Because the user seemed to be annoyed by the fact that the field was blocked/locked until the verification was over, I'm not sure if he got it.

**Comment by mmarsoleta** [comment]
Also, we have a few scenarios of leaving without saving in here if necessary:

https://www.figma.com/design/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?node-id=5816-108475&t=1mm4TyowleOskYbL-4

<img width="450" alt="Screenshot 2024-07-12 at 11 28 47" src="https://github.com/user-attachments/assets/2d3e5ce2-1f82-41b5-b738-9f5b0ad9809e">

**Comment by mgaseta** [comment]
Issues 1, 3 and 5 were fixed under PR #1425

**Comment by mgaseta** [comment]
Moving to blocked until we figure out the fix design for number 4.
