### ISSUE TITLE
update date rules in seedlot registration screens

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1387]
Issue: 

During testing, a user identified a validation rule that needs to be addressed: storage end date can’t start before collection end date (same dates are okay)

In addition, the TSC is concerned about allowing users to enter dates in the future. Submission of estimated/ball park dates could lead to inaccurate dates which has implications for the TSC when trying to understand poor germination or issues with seedlots (storage dates help understand if seed got damaged/moldy) during storage etc. 

Acceptance criteria:

1. storage end date can’t start before collection end date (same dates are okay).
2. dates that occur in the future are not permitted

**Comment by craigyu** [comment]
@SLDonnelly What's considered as future? After user's today?

**Comment by SLDonnelly** [comment]
@craigyu dates after today

**Comment by craigyu** [comment]
> 2. dates that occur in the future are not permitted

what are the "dates" here, all date inputs?
