### ISSUE TITLE
Seedlot registration test: Seedlot 64102 FDI

### ISSUE THREAD

**Issue by mmarsoleta** [bcgov/nr-spar#1390]
For seedlot 64102, the number of SMO parentsfrom outside and geospatial summary is not as expected:

reference:

![Image](https://github.com/user-attachments/assets/3903925c-5556-4458-99e6-db8c6e37bbb6)

test:

![Image](https://github.com/user-attachments/assets/d86741bf-7f58-4a8b-a785-892d08bd81ba)

**Comment by mmarsoleta** [comment]
link to seedlot details: https://nr-spar-test-frontend.apps.silver.devops.gov.bc.ca/seedlots/details/64102

link to reference: 

[63907_FDI.pdf](https://github.com/user-attachments/files/16234637/63907_FDI.pdf)

**Comment by SLDonnelly** [comment]
I checked this seedlot, and it does not have any SMP parents and pollen entered in the third tab. This has produced the differences in SMP parents from outside the orchard between old SPAR and new SPAR. A second test will be run with SMP data to make sure that it matches
