### ISSUE TITLE
🔼 Differences in calculated GW when pollen contamination is applied

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1401]
**Describe the Bug**

There is a diffferent in GW and Ne possibly due to pollen contamination (PC). PC should increase Ne and drop GW. See old SPAR packages for rules. This relies on #1402 

![Image](https://github.com/user-attachments/assets/755958ac-5f4c-4dfe-bf38-4c4446035f69)

**Expected Behaviour**
When pollen contamination is present, we should see an increase in Ne and a drop in GW.

**Acceptance criteria**
1. Pollen contamination drops GW and increases Ne
2. Test cases and unit tests completed
3. Tested and merged

**Comment by RMCampos** [comment]
## GW calculation without pollen (current implementation):

Part 1:
```java
for (List<String> traitCode : traitList) {
  BigDecimal percent = calculateThreshold(allPtList, traitCode);
  if (percent >= 70) {
    BigDecimal genWorthValue = calculateValue(allPtList, traitCode);
  }
}
```

Part 2: (calculateValue function)
```java
BigDecimal malePollenSum = reducePollenCount(traitsDto);
BigDecimal femaleConeSum = reduceConeCount(traitsDto);
BigDecimal sumGw = BigDecimal.ZERO;

for (OrchardParentTreeValsDto dto : traitsDto) {
  BigDecimal traitBreedingValue = getTraitValue(dto, trait);
  if (traitBreedingValue != null && traitBreedingValue != 0) {
    BigDecimal pi = calculatePi(dto.pollenCount(), dto.coneCount(), malePollenSum, femaleConeSum);
    BigDecimal gwValue = traitBreedingValue.multiply(pi);
    sumGw = sumGw.add(gwValue);
  }
}
return sumGw;
```

**Comment by RMCampos** [comment]
Rolled over from Sprint 35.

**Comment by RMCampos** [comment]
@SLDonnelly 

Reviewing changes on this PR, one of the DB columns I flagged to review is `Seedlot.nonOrchardPollenContaminationPercentage`. This column doesn't exist originally in the legacy. So I want to make sure what to store here.

This column exists in the legacy for the `SEEDLOT_PARENT_TREE.NON_ORCHARD_POLLEN_CONTAM_PCT` table though.

Another confusing thought is that the legacy call is **orchard_pollen_contamination_perc** but we have it here as "non_orchard..."

**Comment by SLDonnelly** [comment]
@RMCampos I think that it's picking up another column on the seedlot table in oracle: ![Image](https://github.com/user-attachments/assets/5d0eebd4-4260-492f-adbe-26931e851d3a)

I'm not quite sure that the difference between the two is, I'll keep digging

**Comment by RMCampos** [comment]
@SLDonnelly I guess I got it.

On the Orchard table we have the user's input contaminant percentage. And after the calculation, the value will likely change. And then will be stored in the Seedlot table.

Thank you!
