### ISSUE TITLE
Document pollen contamination rules

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1402]
In order for the new seedlot registration screens to accurately incorporate pollen contamination, we need the package files reviewed and the logic summarized for developers. 

**Definition of Done**
- [ ] Existing logic is reviewed
- [ ] Logic/rules are summarized and posted
- [ ] handoff/review with developers

**Comment by ronrobb** [comment]
@SLDonnelly Can you point me to a format?  
Is this the field of interest?
![image](https://github.com/user-attachments/assets/1bacab82-a7f5-4861-891b-c7b3526e5835)

**Comment by SLDonnelly** [comment]
@ronrobb yes, that is the correct field. I'd like to know from the SPAR legacy package files exactly how pollen contamination is incorporated. Currently, I believe that it only drops the GW. I'm wondering if there is any old code that used to incorporate it with effective population size (Ne). 

Here's are a couple of examples for format: 
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/SMP+Calculation
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/SPR_001A_SMP_CALCULATION+Package+Analysis

**Comment by ronrobb** [comment]
Just collecting notes here.
Calc of Pollen Contamination (%), aka seedlot.orchard_contamination_pct, is calculated by taking the mean of all entered "Non-orchard pollen contam (%)" values on the Parent Tree Origin section of the Parent Tree Contribution page.

**Comment by ronrobb** [comment]
Page created here
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Pollen+Contamination+Calculation+and+Influence+on+Genetic+Worth

**Comment by ronrobb** [comment]
@SLDonnelly Please review and close if satisfied.

**Comment by RMCampos** [comment]
@ronrobb what a documentation! Impressive. Thank you.

**Comment by SLDonnelly** [comment]
@ronrobb, looks great to me!
