### ISSUE TITLE
Inconsistent CORS errors

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#142]
Inconsistent CORS errors are creeping up inconsistently between the Frontend and Backend.  One of many ways to replicate: check the networking tab while clicking a favourite seedlot.

Update: could be the Frontend's preflight request header.
```
Ensure CORS response header values are valid
A cross-origin resource sharing (CORS) request was blocked because of invalid or missing response headers of the request or the associated preflight request .
To fix this issue, ensure the response to the CORS request and/or the associated preflight request are not missing headers and use valid header values.
Note that if an opaque response is sufficient, the request's mode can be set to no-cors to fetch the resource with CORS disabled; that way CORS headers are not required but the response content is inaccessible (opaque).
```

**Comment by DerekRoberts** [comment]
Since this is determined not to be a devops issue I stink at fixing it and am un-assigning myself.  Good luck to whoever's up next!

**Comment by RMCampos** [comment]
We already have a consistent CORS policy and hosts that should be allowed. Closing issue as fixed;
