### ISSUE TITLE
Investigate UI issue brought up during testing

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1420]
Issue:

During testing, it looks like Susan missed a couple of fields in the ownership tab. The submit seedlot button was greyed out and it looks like the UI didn’t provide her with the feedback needed to catch the missing fields. Can you folks review the UI and see if we can make changes to help users along the way? For reference, this is seedlot [64111](https://nr-spar-test-frontend.apps.silver.devops.gov.bc.ca/seedlots/details/64111)

![Image](https://github.com/user-attachments/assets/9f9235d5-b280-47d0-9704-10774a50d09a)

![Image](https://github.com/user-attachments/assets/96b33dd9-14f4-423d-a01e-704f59f39a1b)

**Comment by mmarsoleta** [comment]
[Figma file link](https://www.figma.com/design/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?node-id=8296-43)

**Comment by NicolasLivanos** [comment]
PO & Michelly to write Fixing ticket
