### ISSUE TITLE
text update found by kevin

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1421]
Update some text listed in #1272 

1. 
> Register an a-class seedlot:
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/a6cdd570-9f3d-4dd4-afe0-90613d8deea6)
> 
> 
> 
> - [x] I would remove the subheading "Register a new A-class seedlot" (redundant with heading above) 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226543704)_

2. 
> A-class seedlot created:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/bff96fd6-04de-4794-ac09-7f9018cd5755)
> 
> 
> 
> - [x] Change "Seedlot's main screen" to:
> 
> "Seedlots main screen"
> 
> (removing apostrophe) 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226546586)_

3. 
> Client search modal:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/5357aa40-bb45-4e0e-a33c-a3f1a313fcd7)
> 
> 
> 
> "To view more information about the client, you can go to client search screen."
> 
> 
> 
> - [x] change to:
> 
> 
> 
> "To view more information about the client, go to the client search screen." 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226550062)_

4. 
> Collection methods:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/346579b5-55eb-4590-a880-977ae2b652a9)
> 
> 
> 
> - [ ] Would it make sense to list the collection methods in alphabetical order? 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226555719)_

5. 
> Cone and pollen count:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/f7279894-f585-4652-b9b0-bccf8cfdc72a)
> 
> 
> 
> "Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"
> 
> I would change it to:
> 
> - [x] "Enter the cone and pollen count estimate for the orchard's seedlot"
> 
> 
> 
> 
> 
> SMP success on parent:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/343be4c0-e624-48b6-818e-3ef1e75052e5)
> 
> 
> 
> "Enter the same SMP success on parent or Non-orchard pollent contaminant to all parent trees"
> 
> 
> 
> - [x] I would change "Non-orchard" to "non-orchard"
> 
> 
> 
> 
> 
> Calculation of SMP mix:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/71701239-6c9d-445c-93ea-5836c3d6fff3)
> 
> 
> 
> "Enter the estimative of SMP success for the orchard's seedlot"
> 
> I would change to:
> 
> - [x] "Enter the SMP success estimate for the orchard's seedlot" 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226559587)_

6. 
> File upload:
> 
> 
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/b0e6b4a1-32a7-488c-8b0c-d92e395658fd)
> 
> 
> 
> "Note: When uploading a file all previously filled data within the table will be replaced." 
> 
> Please change to:
> 
> - [x] "Note: When uploading a file, all previously filled data in the table will be replaced." 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226560028)_

7. 
> Breeding value of SMP mix used
> ![Image](https://github.com/user-attachments/assets/600f4d9b-5aa1-4ebe-ac05-277c66e22a2c)
> 
> The subheading is redundant here in my opinion. I would remove that and update the heading to read:
> 
> "Breeding value of SMP mix used on parent" 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226561880)_

8. 
> 
> 
> ![Image](https://github.com/user-attachments/assets/fb3cd27d-d28f-4188-addf-1abd3e87f3f8)
> 
> "SMP Mix geospatial summary"
> 
> Please change to:
> 
> - [x] "SMP mix geospatial summary"
> 
>  

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226562613)_

9. - [ ]
> Step 6:
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/65807895-f6f1-4159-b21d-94427a5da4c1)
> 
> "Enter the extractory agency information and extraction's star and end dates for this seedlot"
> 
> change to:
> 
> - [x] "Enter the extractory agency information and extraction's start and end dates for this seedlot"
> 
> (change "star" to "start")
> 
> 
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/137bd61f-8615-42cb-9148-359199578b93)
> 
> "Enter the seed storage agency information and storage's star and end dates for this seedlot"
> 
> change to:
> 
> - [x] "Enter the seed storage agency information and storage's start and end dates for this seedlot"
> 
> (change "star" to "start")
> 
>  

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226565030)_

10. 
> 
> 
> ![Image](https://github.com/user-attachments/assets/ca677292-d324-4e3c-a634-554fb6bf50ef)
> 
> 
> 
> - [x] Change instances of "Tree Seed Center" to instead read "Tree Seed Centre"
> 
> 
> 
> This one's a bit tricky, but in Canada we use the French spelling of center, so it should actually be "Tree Seed Centre" instead of "Tree Seed Center"
> 
> 
> 
> When Tree Seed Centre comes up in data queries, it is spelled the French way in the database, so it would be nice to keep consistent.
> 
> 
> 
> Hopefully this is more of a find-and-replace kind of function in the front-end 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226566984)_

11.
> Declaration modal:
> 
> 
> 
> ![Image](https://github.com/user-attachments/assets/6cd77c8a-2a63-4e89-acdd-d6cfede8d4db)
> 
> 
> 
> Declaration:
> 
> "Please, be sure to review the content and check if everything is correct with your seedlot registration.
> 
> Go to first step and review the form."
> 
> 
> 
> Please change to:
> 
> - [x] "Please review this form to ensure the information is correct for this seedlot registration.
> 
> Click here to go back to the first step."
> 
> 
> 
> 
> 
> And then have "Click here" link to the first step in the form 

 _Originally posted by @kevinginley in [#1272](https://github.com/bcgov/nr-spar/issues/1272#issuecomment-2226571645)_

**Comment by ngunner15** [comment]
1.

> Do we want to remove the subtitle for the favorite card too?
> @kevinginley 
> ![Image](https://github.com/user-attachments/assets/395d2cfd-eee1-4453-96d2-cca8f52e62e5)

**Comment by kevinginley** [comment]
Yes, thank you!

**Comment by ngunner15** [comment]
Reduced story point from 2 > 1, less complicated task.

**Comment by kevinginley** [comment]
@ngunner15 
Looking good! A few remaining changes:
Client search

Please change "go to client search screen." to: 
"go to the client search screen."

When I click "go to client search screen", it didn't take me anywhere. Also, I'm confused, because aren't we already on the client search screen?

Step 5:

I requested
"Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"

be changed to:
"Enter the cone and pollen count estimate for the orchard's seedlot"

My apologies - I didn't mean to remove "(*required)". Can you please update it to read:
"Enter the cone and pollen count estimate for the orchard's seedlot (*required)"


Please update the heading from
"Breeding value of SMP mix used" to:
"Breeding value of SMP mix used on parent"

and remove the subheading "Check the breeding value of SMP mix used on parent:

Step 6 -
"Click here" should link to the first step in the current form, if possible.

Thank you

**Comment by kevinginley** [comment]
Not sure if this is the right ticket to bring this up, but I noticed some funky text alignment issues on Step 5 when I had SPAR only take up half of my screen.
![image](https://github.com/user-attachments/assets/403aa605-efd5-42d1-afeb-80fdd6877e93)

and also the placement of the search button alignment is looking a little funny in client search:
![clientsearch_button-alignment](https://github.com/user-attachments/assets/34d005f7-24e3-405b-9360-783e2e964c13)

**Comment by ngunner15** [comment]
> [@ngunner15](https://github.com/ngunner15) Looking good! A few remaining changes: Client search
> 
> Please change "go to client search screen." to: "go to the client search screen."
> 
> When I click "go to client search screen", it didn't take me anywhere. Also, I'm confused, because aren't we already on the client search screen?
> 
> Step 5:
> 
> I requested "Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"
> 
> be changed to: "Enter the cone and pollen count estimate for the orchard's seedlot"
> 
> My apologies - I didn't mean to remove "(*required)". Can you please update it to read: "Enter the cone and pollen count estimate for the orchard's seedlot (*required)"
> 
> Please update the heading from "Breeding value of SMP mix used" to: "Breeding value of SMP mix used on parent"
> 
> and remove the subheading "Check the breeding value of SMP mix used on parent:
> 
> Step 6 - "Click here" should link to the first step in the current form, if possible.
> 
> Thank you

Completed all changes except Step 6, I will need more time to figure out how to add a link.

**Comment by ngunner15** [comment]
[<ToastNotification>](https://svelte.carbondesignsystem.com/components/ToastNotification)
I'm not able to add a link to this component

**Comment by ngunner15** [comment]
> > [@ngunner15](https://github.com/ngunner15) Looking good! A few remaining changes: Client search
> > Please change "go to client search screen." to: "go to the client search screen."
> > When I click "go to client search screen", it didn't take me anywhere. Also, I'm confused, because aren't we already on the client search screen?
> > Step 5:
> > I requested "Enter the estimative of Cone and pollen count for the orchard's seedlot (*required)"
> > be changed to: "Enter the cone and pollen count estimate for the orchard's seedlot"
> > My apologies - I didn't mean to remove "(*required)". Can you please update it to read: "Enter the cone and pollen count estimate for the orchard's seedlot (*required)"
> > Please update the heading from "Breeding value of SMP mix used" to: "Breeding value of SMP mix used on parent"
> > and remove the subheading "Check the breeding value of SMP mix used on parent:
> > Step 6 - "Click here" should link to the first step in the current form, if possible.
> > Thank you
> 
> Completed all changes except Step 6, I will need more time to figure out how to add a link.

To be completed by @mgaseta
