### ISSUE TITLE
🔼 Investigate SMP calculation

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1422]
## User Story
As an orchard manager/technician, I want to know the genetic worth, mean latitude, mean longitude and mean elevation of supplemental mass pollination (SMP) that I apply on my orchard.

Implementation of SMP calculations will be address in #1498 

## Acceptance Criteria
- Clear understanding of the calculations and all dependencies, tables, required
- Given that I enter the parent tree number and pollen volume in the SMP tab of the seedlot registration, the application calculates the genetic worth, mean latitude, mean longitude and mean elevation of supplemental mass pollination (SMP) that I apply on my orchard.
- Business rule: The parent trees used in an SMP mix can be from outside of the orchard but are registered parent trees of the correct species.

Definition of Done:

- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by NicolasLivanos** [comment]
PO + Craig + Mattheus tmr at 1PM?
