### ISSUE TITLE
Different parent tree GW values + utc date changes

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1435]
investigate the get parent tree by vegcode endpoint and its sql query, find out why the gw values for certain trees are different

![Image](https://github.com/user-attachments/assets/1ec1e535-933b-44a8-a45f-a25f9bb4fda5)

![Image](https://github.com/user-attachments/assets/1c97d163-dc49-4ec6-b5f4-30f910c62489)

example from SX PG LOW

**Investigation complete**

Task:

- we need to fetch parent trees with the new updated sql query provided by Ron
- display parent tree that matches primary orchard's SPU, if a parent tree exist in the secondary orchard but not in primary orchard, use default values
- if no genetic worth value is present, use default values (this requires a new table on postgres, or hardcoded in a way that's easy to maintain)
- make a new endpoint `/orchards/vegetation-code/{vegCode}` on postgres api, which calls the same endpoint on Oracle, but adds the spu to that object

**Comment by RMCampos** [comment]
Spotted that bug again, when trying to edit the seedlot on the review form.

- File: `frontend/src/views/Seedlot/ContextContainerClassA/utils.ts`
- Inside `convertParentTree` function, inside Object.keys, when pushing to the parentTreePayload, at this line: `parentTreeId: parentTreeData.allParentTreeData[key].parentTreeId,` (here: https://github.com/bcgov/nr-spar/blob/main/frontend/src/views/Seedlot/ContextContainerClassA/utils.ts#L942)
- Species: FDC
- Orchard: 405
- Parent tree ID not found: 37

Logging from the application
Condition:
```javascript
if (!parentTreeData.allParentTreeData[key]) {
  console.log('no parentTreeData.allParentTreeData[key] for key', key);
  console.log('parentTreeData.tableRowData', JSON.stringify(parentTreeData.tableRowData));
  console.log('parentTreeData.allParentTreeData', JSON.stringify(parentTreeData.allParentTreeData));
  console.log('Object.keys(parentTreeData.tableRowData)', JSON.stringify(Object.keys(parentTreeData.tableRowData)));
}
```

Result
```
no parentTreeData.allParentTreeData[key] for key 37
parentTreeData.tableRowData {"37": ...} (added file Log-line-two.txt)
parentTreeData.allParentTreeData {}
Object.keys(parentTreeData.tableRowData) ["37","69","101","129","192","202","212","239","241","300","327","508","568","760","969","970","3141","3144","3169","3171","3210","3245","3247","3400","3427","3428","3431","3432","3455","3500","3518","3524","3552","3846","3847","3848","3849","3853","3856","3887","3915","3941","3942","3947","3948","3949","3950","3951","3954","3955","3957","3958","3959","3960","3961","3983","3986","3987","3988","3989","3990","5004","5005","5014","5016","5019","5027","5030","5032","5033","5036","5037","5040","5041","5046","5049","5050","5051","5055","5057","5058","5059","5065","5068","5077","5078","5086","5087","5090","5094","5100","5104","5110","5112","5113","5114","5118","5119","5126","5128","5134","5136","5137","5139","5142","5143","5149","5153","5154","5302","5306","5307","5312","5314","5325","5328","5331"]
```

Attachment file:

[log-line-two.txt](https://github.com/user-attachments/files/16432995/log-line-two.txt)

**Comment by craigyu** [comment]
Implementation done in #1491, needs to add/modify tests still

**Comment by craigyu** [comment]
need tests still
