### ISSUE TITLE
SMP success on parent(Step 5, part 2) Cypress Test

### ISSUE THREAD

**Issue by ngunner15** [bcgov/nr-spar#1454]
Write Cypress test for `Step 5` of the Parent tree and SMP test plan. Check details here - https://github.com/bcgov/nr-spar/issues/1440

- Needs #1594

**Comment by ngunner15** [comment]
Add save progress code inside then block of Client search modal.
Separate status check code to its own it block.

**Comment by ngunner15** [comment]
Orchard page dropdown functionality changed, need to confirm if those changes are permanent.

**Comment by ngunner15** [comment]
There is buggy behavior on the orchard step, will need to resolve that to finish this ticket.

**Comment by SLDonnelly** [comment]
RO into 36
