### ISSUE TITLE
Primary and Secondary Orchard selection

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#1459]
![Image](https://github.com/user-attachments/assets/f7457d30-11e3-4882-88cc-c11ace05d297)

Modify the orchard selection process, have
- A primary orchard selection *required
- A secondary orchard selection

Modify the validation logic
Modify the parent tree step's display PTs by orchard logic

**Comment by mgaseta** [comment]
Closing it, since it's in the done column.
