### ISSUE TITLE
Enhance parent tree bigquery

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#1495]
## User Story
As a user, I want to have a quick response when getting Parent Tree data.

## Acceptance Criteria
- Modify query or improve workflow splitting into two queries.
- SQL query: https://github.com/bcgov/nr-spar/blob/main/oracle-api/src/main/java/ca/bc/gov/oracleapi/repository/ParentTreeRepository.java#L15

**Comment by SLDonnelly** [comment]
RO into 36
