### ISSUE TITLE
Favourite cards overflow menu not working

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#1563]
## User Story
As a user, I want to be able to highlight and delete a saved Favourite page in the Dashboard page. Currently when clicking at the three dots menu, instead of showing up highlight and delete options, it's sending user to the actual favourite page destination.

## Acceptance Criteria
- Menu displaying as expected
- Options working, making available highlight and remove favourite cards;

**Comment by mgaseta** [comment]
Not reproducible anymore, fixed on #1545
