### ISSUE TITLE
Test alerting system on legacy SPAR OpenSearch

### ISSUE THREAD

**Issue by xiaopeng0202** [bcgov/nr-spar#1608]
---
**Describe the task**
Enable the alerting system on the legacy SPAR OpenSearch instance to monitor key metrics and trigger notifications for defined thresholds. 

**Acceptance Criteria**
- [ ] Simulated test conditions successfully trigger alerts based on predefined thresholds
- [ ] Notifications are delivered to the correct recipients or channels (e.g., email, teams) without delay
- [ ] All alerts and notifications are logged, and their performance (accuracy and timeliness) is reviewed and validated
- [ ] Ensure notification channels are configured correctly and are capable of handling the alert load

**Comment by SLDonnelly** [comment]
next step to send alerting to teams, will create a new ticket
