### ISSUE TITLE
Serve Frontend with Caddy

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#161]
Let Caddy serve static files. Better performance and lower resource utilization than most other options. Also more or less a standard thing to do.

Copied from bcgov/nr-spar-webapp, which was archived.

https://github.com/bcgov/nr-spar-webapp/issues/48

**Comment by DerekRoberts** [comment]
https://caddyserver.com/docs/caddyfile/concepts
https://caddyserver.com/docs/quick-starts/caddyfile
https://caddy.community/t/caddy-lab-setup-examples/15915

**Comment by DerekRoberts** [comment]
There has been progress on Caddy, but I could use a hand.  @SLDonnelly, could @RMCampos please help?

**Comment by RMCampos** [comment]
I'll take a look on this. Thanks @DerekRoberts
