### ISSUE TITLE
Notification for greyed out submission button

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1610]
**As an**orchard manager/technician** **I want** *a banner or notification that explains why the submit button is greyed out**So That** *I know how to correct any issues in my registration form*

**Acceptance Criteria**
- [ ] Given that there are empty field, When a user tries to click the submit button it is greyed out, Then they are given a warning message that directs them to reconcile empty fields.

**Additional Context**
Figma file here: https://www.figma.com/design/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?node-id=8296-43
-just use option one

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] QA from UX
- [ ] Merged

**Comment by mgaseta** [comment]
Blocked due to issues with the client agency and location code fields.

**Comment by SLDonnelly** [comment]
RO to sprint 39
