### ISSUE TITLE
Add trigger to ETL pipeline to prevent over-writting of data

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1693]
Issue:

The ETL pipeline is at risk of overwriting seedlot ownership quantity data what was added to the table after initial registration. 

Task:

We need to prevent the ETL from writing to the seedlot_owner_quantity table in oracle once the condition for this trigger, SEEDLOT.ORIGINAL_SEED_QTY > 0, is met.

Acceptance Criteria:

- [ ] Solution functions as outlined above and prevents over-writing
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by NicolasLivanos** [comment]
Kevin N to review, test, approve

**Comment by SLDonnelly** [comment]
@franTarkenton @xiaopeng0202 do we have an ETA for this? The business area has asked for an update for when it will be merged
