### ISSUE TITLE
[Bug] Changing status when editing seedlot on review page

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#1698]
**Describe the Bug**
The seedlot status is changing whenever the admin makes a change and save it. 

**Expected Behaviour**
Status should stay the same after editing it.

**Actual Behaviour**
Status always going back to pending.

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to an `Approved` or `Complete` seedlot
2. Click the button to edit it
3. Change a field
4. Click the save butotn
5. Notice the status is back to `Submitted`

**Comment by SLDonnelly** [comment]
@mgaseta I registered a seedlot and got it into Approved status. When I updated a comment on the form in APP status, it stayed that way after saving so it looks like this is good. We will need to get this into test/production to see if it works on COM status seedlots too
