### ISSUE TITLE
WCAG standards landing dashboard

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1723]
**As a** *SPAR User* **I want** *SPAR to follow WCAG standards* **So That** *I can use assistive technologies to help me complete my work*

**Acceptance Criteria**

For the SPAR landing dashboard
![image](https://github.com/user-attachments/assets/8cb45daf-56af-4bfb-baaf-299a6d72de2d)

- [x] Semantic HTML structure
- [x] Ensure all images have alternative text (for the photo on the log in screen use: "Picture of spruce tree branches with needles and cones".
- [x] Accessible forms
- [ ] Keyboard navigation
- [x] ARIA (Accessible Rich Internet Applications) roles and attributes
- [ ] Focus management
- [x] Contrast above 4.5:1
- [x] Tested - Use accessibility tools and screen readers during development.
   
**Additional Context**
- More information here: https://github.com/bcgov/nr-spar/wiki/Coding-for-accessibility:-Screen-readers

**Definition of Done**
- [x] Ready to Demo in Sprint Review
- [x] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [x] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [x] QA from UX team member
- [ ] Merged

**Comment by ngunner15** [comment]
Read up on how to make Loading animation screen reader-friendly and sematic.

**Comment by kevinginley** [comment]
@ngunner15 Looks good to me! I also ran through it with a screen reader (NVDA) and it seemed to work well.
