### ISSUE TITLE
UI library testing

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1741]
Using Xiao's Template team members will access the following PRs:

https://github.com/bcgov/nr-spar/pull/1733
https://github.com/bcgov/nr-spar/pull/1734
https://github.com/bcgov/nr-spar/pull/1735

**Comment by ngunner15** [comment]
[UI_Library_Evaluation_Nisarg.xlsx](https://github.com/user-attachments/files/18028329/UI_Library_Evaluation_Nisarg.xlsx)
