### ISSUE TITLE
Update CONSEP MMP2 screen designs based on TSC feedback

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#1778]
**Describe the task**
Update CONSEP MMP2 lo-fi wireframes based on feedback received by TSC users during our review workshop on December 12th.

**Acceptance Criteria**
- [ ] Update lo-fi wireframes in Mural

**SME/User Contact**
Victoria L.

**Comment by SLDonnelly** [comment]
duplicate ticket
