### ISSUE TITLE
SPIKE: Collapse Navigation Panel - Timeboxed 2 hours

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#1780]
Carbon's components doesn't have the functionality to make the navigation panel collapsible out of the box (as reported on [this issue](https://github.com/carbon-design-system/carbon/issues/10208)), so we need to take some time to investigate the right way to do this.

**Comment by mgaseta** [comment]
Spike completed, found a way to overcome carbon's behavior
