### ISSUE TITLE
My Seedlots bug fixes (1/2)

### ISSUE THREAD

**Issue by ArthurEncr** [bcgov/nr-spar#179]
These changes in My Seedlot screen will be implemented in this issue:

- Subtitle wrong should be "Check and manage your own seedlots"
- Column wrong should be "Seedlot class", "Seedlot species" and "Last updated"
- Hover doesn't change to clickable object on My seedlots table
- Icons go/back next page on My seedlots page/table are misaligned
- Background color on "table title" is wrong on My seedlots page
- Line color above "table title" is wrong
- Use constants.ts

**Comment by craigyu** [comment]
Please make sure the PR is merged before moving it to Done, the PR is still open at the moment
