### ISSUE TITLE
Fix Seedlot Species combo box in the Application Agency Screen

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#185]
Description:

In the Seedlot Species field of the applicant agency section of the A class registration form, the drop down menu is not showing the species code and description anymore.

Acceptance Criteria:
The expected behaviour for this is for the Species code and species name to appear in the dropbox/combobox. Unused vegcodes are filtered out from the options shown (as per [FSADT2-637](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-637))

**Comment by RMCampos** [comment]
This was fixed when backend api got back working.
