### ISSUE TITLE
Test Frontend Responsiveness [tracking]

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#193]
**Describe the task**
Responsiveness maybe a bit broken after recent changes, this task is to look and list the issues, if any is found.

**Additional Comment**
- Just an idea, but we can try using SASS to define vars and change them according with the viewport size, examples:
  1. https://teamtreehouse.com/community/sass-scss-how-can-i-make-a-variable-change-values-with-different-media-queries
  2. https://stackoverflow.com/questions/9122195/using-sass-variables-with-css3-media-queries

**Comment by SLDonnelly** [comment]
Matheus believes that most of these are done, but a double check will need to be done. Low priority

**Comment by craigyu** [comment]
Write a wiki page on frontend responsiveness.

**Comment by ArthurEncr** [comment]
List of errors found
[Frontend Responsiveness (Register A Class seedlot) #771](https://github.com/bcgov/nr-spar/issues/771)
[Frontend Responsiveness (My seedlots) #772](https://github.com/bcgov/nr-spar/issues/772)
[Frontend Responsiveness (Complete seedlot register) #773](https://github.com/bcgov/nr-spar/issues/773)
[Frontend Responsiveness (Seedlot details) #774](https://github.com/bcgov/nr-spar/issues/774)
[Frontend Responsiveness (Main dashboard) #768](https://github.com/bcgov/nr-spar/issues/768)
[Frontend Responsiveness (Seedlot dashboard) #769](https://github.com/bcgov/nr-spar/issues/769)
[Frontend Responsiveness (Feedback page) #770](https://github.com/bcgov/nr-spar/issues/770)
