### ISSUE TITLE
Orchard step pollen information section not working properly

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#199]
**Describe the Bug**
Orchard step pollen information section not working properly.

**Expected Behaviour**
"Contaminant pollen breeding percentage" and "Contaminant pollen methodology" fields should only show when the "Was pollen contamination present?" field is set to false. Also, the "Contaminant pollen methodology" field should be true and read-only.

**Actual Behaviour**
All fields are appearing no matter the value set on "Was pollen contamination present?" and "Contaminant pollen methodology" field is not read-only.

** Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to Orchard Step when registering a seedlot
2. The fields will appear

**Screenshots**
![image](https://github.com/bcgov/nr-spar/assets/105936322/d203a13f-26ec-4161-89b6-2db8d156ea3c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 113.0.5672.127

**Comment by SLDonnelly** [comment]
Hello @mgaseta, while you are working on this ticket, would it be possible to change the label from "Contaminant pollen breeding percentage (optional) %" to "Contaminant pollen breeding value (optional)". Let me know if you prefer that I make a separate ticket for this change

**Comment by mgaseta** [comment]
Hey @SLDonnelly , it can be done on this ticket, it's a small change and stays in the same context of the ticket. Thank you!
