### ISSUE TITLE
Genetic Worth calculation API development

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#240]
Implement the calculation of the genetic worth of a seedlot

Implement the calculation of the genetic worth of a seedlot according to the formula of the attached workbook.

Genetic worth

Genetic worth, as defined in [Chief Forester's Standards for Seed Use](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/tree-seed/legislation-standards/current-standards/consolidated_cf_stds__amended_1apr2022.pdf), is "a measure of a lot's genetic worth, with respect to a specific trait". In quantitative terms, a seedlot's genetic worth with respect to a genetic trait B is the weighted average of the genetic value of B of all the trees that contributed with seeds to that lot; the weights in this case is the proportion of cones and pollen each tree has given to the creation of these seeds in relation to the total of cones and pollen used to create the seeds. So the genetic worth of a seedlot with respect to the genetic trait B is given by the formula

GB = B1*(M1 + F1)/2 + ... + Bn*(Mn + Fn)/2

where

Bi is the quantification of tree i's genetic trait B
Mi is the proportion of pollen that tree i has contributed to the generation of this seedlot in relation to the total of pollen given by all trees
Fi is the proportion of cones that tree i has contributed to the generation of this seedlot in relation to the total of cones given by all trees
Pollen contamination

There are cases where we either know or think that the pollen given by one of the trees isn't entirely its own, and the provenance of that pollen is unknown to us. When this happens, we must discard the foreign pollen when calculating the genetic contribution of that tree to the seedlot, so we get to a new formula

GB = BC1*C1 + B1*(M1*(1 - C1) + F1)/2 + ... + BCn*Cn + Bn*(Mn*(1 - Cn) + Fn)/2

where Ci is the estimated percentage of foreign pollen in the tree i's contribution and BCi is the estimated quantification of the contaminant pollen from tree i.

We'll cover these cases for now, so this is the formula we'll be using in this task.

Implementation

We can get the information we need from the following entities:

Pollen contamination, cone and pollen contribution from SeedlotParentTree
Genetic trait quantification from ParentTreeTreeGeneticQualityDto (obtainable from [this endpoint from the Oracle API](https://nr-spar-test-oracle-api.apps.silver.devops.gov.bc.ca/swagger-ui/index.html#/orchard/getParentTreeGeneticQualityData)

We still need to figure out where to get the quantification of the genetic trait for the contaminant pollen.

[PR #156](https://github.com/bcgov/nr-spar/pull/156) contains the work made so far.

Created from task: https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-507

**Comment by RMCampos** [comment]
Moving to blocked, due to pending questions regarding the table edition and flow. Next Monday (July 17th) we should discuss this task on the Dev Collab Meeting.

**Comment by thiagosanchezenc** [comment]
Spoke to Sabina about the 70% rule, it is applied for each trait and it should consider not the number of tested parent trees but the amount of material contributing to the seedlot. In other words, it should take into account the percentage of material (pollen and cone count) that was tested for each trait.

**Comment by RMCampos** [comment]
@SLDonnelly two questions for today

- If the Seedlot source is UPT (Untested Parent Tree)? Should we do the calculations?
- And for the other options, like "to be registered" and "collected from BC source", they affect the calculations in any way?

**Comment by SLDonnelly** [comment]
1. If Class A Source = "Untested" or Class A Source = "Custom"
  GW-G = 2
  GW-D = 0
  GW-R = 0
Else
  ROUND(SUM([Total Parent (seed) GW contrib to seedlot]
  
  <html><body>


  | Total Parent (seed) GW contrib to seedlot: |  
-- | -- | --
  | Certification Template Col: | AD
  | Data Source: | Interim calculation - not stored
  | Derivation: | If Total Pollen Count = 0          Female GW contribution        Else          (Female GW contribution + Total male GW contribution)        / 2


</body>
</html>

**Comment by RMCampos** [comment]
@craigyu and @mgaseta 

I think we could have this (initial) format for sending the step 5 data (with pollen and cone count):

```json
[{
  "parentTreeNumber": "37",
  "coneCount": 123,
  "pollenCount": 123,
  "geneticTraits": [
    {
      "code": "DFW",
      "type": "BV", // or "CV" -> Breeding value or Clonal value. I'm asking Sabina if we need to send this type.
      "value": 11
    },
    {
      "code": "GVO",
      "type": "BV",
      "value": 16
    },
    {
      "code": "WWD",
      "type": "BV",
      "value": 5
    }
  ]
}]
```

**Comment by craigyu** [comment]
if clonal value is not needed, the following format is easier for front-end to generate, but I can see the challenge of it for back-end
```json
[{
  "parentTreeNumber": "37",
  "coneCount": 123,
  "pollenCount": 123,
  "dfw": 11,
  "gvo": 16,
  "wwd": 5
}]
```

**Comment by RMCampos** [comment]
@craigyu 🤔 indeed. I like Option 1. We can have optional fields, no problem. It's actually simpler. Thanks :)

**Comment by RMCampos** [comment]
API response sample:

```json
{
  "effectivePopulationSizeNe": 0,
  "coancestry": 0,
  "numberOfSmpParentFromOutside": 0,
  "traits":  [
    {
      "trait:": "gvo",
      "volumeGrowth": "0",
      "percentage": 55.2
    }
  ]
}
```

**Comment by RMCampos** [comment]
API request body sample:

```json
[
  {
    "parentTreeNumber": "129",
    "coneCount": 13,
    "pollenCount": 48.5,
    "geneticTraits": [
      { "traitCode": "gvo", "traitValue": 18 },
      { "traitCode": "wwd", "traitValue": -2.2 },
    ]
  },
  {
    "parentTreeNumber": "212",
    "coneCount": 8.5,
    "pollenCount": 49,
    "geneticTraits": [
      { "traitCode": "gvo", "traitValue": 20 },
      { "traitCode": "wwd", "traitValue": 1.7 },
    ]
  }
]
```
