### ISSUE TITLE
Auto refresh loop on landing page

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#242]
## Environment

- Local only

## Steps to Reproduce

- Start the webapp server locally
- Go to http://localhost:3000/ on any browser(chrome incognito included) other than chrome

## Current Behaviour

The web page auto refreshes itself indefinitely by trying to reach the url below, each refresh has a different state param

- http://localhost:3000/#error=login_required&state=7378a922-ca94-4e34-b52f-a376f356f483

## Expected Behaviour

- No refresh

**Comment by craigyu** [comment]
Fixed wit FAM
