### ISSUE TITLE
Remove {seedlotNumber} in upload endpoints

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#280]
## Description

Remove `{seedlotNumber}` from both `/api/seedlots/{seedlotNumber}/parent-trees-contribution/cone-pollen-count-table/upload` and `/api/seedlots/{seedlotNumber}/parent-trees-contribution/smp-calculation-table/upload` APIs.

- Update `ParentTreesContributionEndpoint` class on `Backend API`, removing all references to the SeedlotNumber and variables.
- Make sure all tests are still passing;

**Comment by RMCampos** [comment]
Waiting for @thiagosanchezenc to get back so we can confirm that this number will not be used in the backend.

**Comment by mgaseta** [comment]
Confirmed with @thiagosanchezenc, we can safely remove it.
