### ISSUE TITLE
Create Applicant Agency API

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#323]
Questions to clarify this change:

1. There will be a default Applicant Agency for the users? if yes, where this data will come from?
2. Users can change the default one? If yes, we may need to update our ForestClient API to fetch this data.

**Comment by RMCampos** [comment]
ForestClient Swagger: https://nr-forest-client-api-prod-backend.apps.silver.devops.gov.bc.ca/v3/swagger-ui/index.html#/Client%20API/listClientLocations

**Comment by RMCampos** [comment]
Quick call on Friday with Sabina and the team:

- Yes, the user will have one (or more) profiles tied to his account. 
- Users can't choose applicant agency other than the ones tied to their account.
- However user do can change the location code. There will be a default, but they can change.

Changes for this task:

- Create an API to provide a list of Locations Code given a Client Number;

(I suggest we allow any inputs as Client Acronym until we have all profiles and default values working)

cc: @mgaseta and @craigyu

**Comment by mgaseta** [comment]
This is current blocked since we can't fetch the user's Applicant Agencies. 

For now, we decided to go with a mock API for Applicant Agencies and an API exclusively for Location Codes, for more details please see tasks: #350 and  #351

**Comment by craigyu** [comment]
closed by #500
