### ISSUE TITLE
"Class A source" or "A Class source"

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#331]
On the first screen to register a new Seedlot, just below the Seedlot Species, there's the source. I wonder if we should fix the order, or is this correct?

![Image](https://github.com/bcgov/nr-spar/assets/2219519/208ad777-fa73-473b-a09d-c4a64bedd2ea)

**Comment by mgaseta** [comment]
@SLDonnelly is the fix necessary here? If so, it's a 1 point task we could fill in sprint 15 :)

**Comment by SLDonnelly** [comment]
Hi @mgaseta, I will reach out to the business area and confirm whether they want A class or Class A. We can keep this as a 1 point filler for 15 for the time being

**Comment by RMCampos** [comment]
@SLDonnelly any updates on this one?

**Comment by SLDonnelly** [comment]
Hello @RMCampos and @mgaseta, this inquiry has actually sparked a bit of a debate!! there's been some back and forth about switching to orchard seed and natural stand seed but nothing confirmed. I think for now we can stick with "Class A source"

**Comment by RMCampos** [comment]
Np. Closing this issue then, for now. 👍🏻 😃
