### ISSUE TITLE
Create Flyway Migration files to create and seed tables

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#341]
#### This is a sub task of #340 and has to be done before #342 

Keep the following as Enums in `./backend/src/.../enums` and convert others to tables
1. LatitudeCodeEnum.java
2. LongitudeCodeEnum.java 

Definition of Done:
- Migration files created and tables are seeded with default data

#### NOTE:
DROPPED COLUMN in migration V16
```sql
alter table spar.seedlot_orchard drop column primary_ind;
```

**Comment by thiagosanchezenc** [comment]
Just sent @craigyu the scripts.

**Comment by craigyu** [comment]
These files will be uploaded with #342 as there is no need to open a PR, this will be marked as done
