### ISSUE TITLE
Synthesis and summary

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#371]

**Comment by kevinginley** [comment]
of Lean Inception Workshop results for interested parties

**Comment by SLDonnelly** [comment]
old roll over tickets from previous releases can be found here: https://apps.nrs.gov.bc.ca/int/jira/projects/SPAR/versions/19389

**Comment by kevinginley** [comment]
Data synthesis spreadsheet and summary document can be found [here](https://bcgov.sharepoint.com/teams/07176/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=F941Jj&xsdata=MDV8MDF8fGQzMmUyZjEwMmRlNDQ2ZWEwNDIyMDhkYjkyMDg0NjJlfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2MzgyNjQzMzY0Mzc4NzE2NTB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbUUxTm1OaE16ZGpOems1TWpReVptUmlOamcyT0dRMU9UQTNabUU1WTJKaFFIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOamt3T0RNMk9EUXpNemsyfDhjY2MzMTZmNzdhYTQ1NzUwNDIyMDhkYjkyMDg0NjJlfDFkMTgzNTk0ZDVjNjQxOWVhNzAzNWNlYjYyMjZhOWNm&sdata=ai93NE5yV1hUN0w3c0JrenVtOFhvSFNuSWlMYXc1bVJPRTdac1d3c0pUMD0%3D&ovuser=6fdb5200%2D3d0d%2D4a8a%2Db036%2Dd3685e359adc%2CKevin%2EGinley%40gov%2Ebc%2Eca&OR=Teams%2DHL&CT=1690836898684&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA3MDMwNzMzMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=eb84a153%2Df308%2D4b11%2Dbc36%2Dd01956768f69&FolderCTID=0x012000FA3251F1A04DD243BC03068DE28A7596&id=%2Fteams%2F07176%2FShared%20Documents%2FGeneral%2FUX%20Team%2FSPAR%20%26%20CONSEP%20%281%29%2FWorkshop%20%2D%20Lean%20Inception&viewid=5aa3a2e5%2D1763%2D4926%2Db3ee%2Ddfae72eabd59).

Now I'm working on some slides with a very high-level overview of the feature prioritization voting results

**Comment by kevinginley** [comment]
Added the summary slides in [that same folder](Data synthesis spreadsheet and summary document can be found [here](https://bcgov.sharepoint.com/teams/07176/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=F941Jj&xsdata=MDV8MDF8fGQzMmUyZjEwMmRlNDQ2ZWEwNDIyMDhkYjkyMDg0NjJlfDZmZGI1MjAwM2QwZDRhOGFiMDM2ZDM2ODVlMzU5YWRjfDB8MHw2MzgyNjQzMzY0Mzc4NzE2NTB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPbUUxTm1OaE16ZGpOems1TWpReVptUmlOamcyT0dRMU9UQTNabUU1WTJKaFFIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOamt3T0RNMk9EUXpNemsyfDhjY2MzMTZmNzdhYTQ1NzUwNDIyMDhkYjkyMDg0NjJlfDFkMTgzNTk0ZDVjNjQxOWVhNzAzNWNlYjYyMjZhOWNm&sdata=ai93NE5yV1hUN0w3c0JrenVtOFhvSFNuSWlMYXc1bVJPRTdac1d3c0pUMD0%3D&ovuser=6fdb5200%2D3d0d%2D4a8a%2Db036%2Dd3685e359adc%2CKevin%2EGinley%40gov%2Ebc%2Eca&OR=Teams%2DHL&CT=1690836898684&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA3MDMwNzMzMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=eb84a153%2Df308%2D4b11%2Dbc36%2Dd01956768f69&FolderCTID=0x012000FA3251F1A04DD243BC03068DE28A7596&id=%2Fteams%2F07176%2FShared%20Documents%2FGeneral%2FUX%20Team%2FSPAR%20%26%20CONSEP%20%281%29%2FWorkshop%20%2D%20Lean%20Inception&viewid=5aa3a2e5%2D1763%2D4926%2Db3ee%2Ddfae72eabd59).).
