### ISSUE TITLE
Create modal search for Client Information

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#447]
Task:

A Modal Client Search function needs to be developed to allow users to look up client numbers. 

![Image](https://user-images.githubusercontent.com/64149835/265816292-4bd717cc-fb02-4326-957e-254f402051f3.png)

Acceptance Criteria:
[ ] Paginated search output
[ ] Users can look up by name, acronym, client number

**Comment by thiagosanchezenc** [comment]
Subtasks related to the issue:
#497 
#498 
#499
