### ISSUE TITLE
Step 3 Validation FE

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#452]
Criteria:

- [ ] Validation of user inputs
- [ ] Ensure all mandatory fields are filled in

**Comment by mgaseta** [comment]
After discussions with the team regarding optional or non-optional fields for the storage section and how to get the proper behavior for using collector agency, this task got more complex, so I'm raising it to 5 points.

**Comment by mgaseta** [comment]
The behavior/look of this step changed again... Setting back to 3 points and will create a new task to deal with the new styling.
