### ISSUE TITLE
SMP calculation Mix API integration with front end

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#459]
**Describe the task**
The SMP calculation mix API will be integrated with the front end

**Acceptance Criteria**
- [ ] SMP mix correctly calculating and showing data on the front end
- [ ] Relevent documentation updated

**Comment by craigyu** [comment]
Need to discuss the button issue with designers

**Comment by craigyu** [comment]
Upgraded to 3 point as this ticket includes changes to front end

**Comment by craigyu** [comment]
Rolled over from sprint 26

**Comment by craigyu** [comment]
waiting for design update

**Comment by craigyu** [comment]
design updated in #905

**Comment by craigyu** [comment]
rolled over from sprint 27
