### ISSUE TITLE
Edit applicant information workflow needs to be completed (FE and BE)

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#463]
**Describe the task**
The "edit applicant information" workflow needs to be completed. 
**Acceptance Criteria**
- [ ] Once a seedlot number is generated, the user can edit the applicant information.
- [ ] When a user clicks on the edit applicant button, they can update the information
- [ ] One rule to keep in mind, if the user has already entered the orchard information and they want to change the species of the seedlot, they will need to get a notification 1) either that this action is blocked, or 2) orchard and parent tree contribution data will be cleared

![Image](https://github.com/bcgov/nr-spar/assets/64149835/1d9e7b43-9361-4a24-b7fc-91fb2888a7ba)

**Additional context**
- Add any other context about the task here.
- Or here

**Comment by thiagosanchezenc** [comment]
To be confirmed with UX folks - show a message once the user changes the species to inform that all data will be lost/clean, that way we can keep the seedlot number and it would be easier to make it work both on frontend and backend.

**Comment by thiagosanchezenc** [comment]
Subtasks related to the issue:
