### ISSUE TITLE
[Cancelled] species changes in Applicant Information section

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#464]
**Describe the task**

UX task to determine how to handle changes to the application information section after the orchard and parent tree data have been entered. Do we:

1. Block users from updating applicant information or species information when they have begun entering data in other screens or, 
2. Notify users that data from all other screens will be cleared or, 
3. hybrid approach where some data is entered (defaults that pertain to the applicant agency) and some is cleared (orchard and parent tree data if species is cleared)

**Comment by craigyu** [comment]
not allowing users to do this anymore
