### ISSUE TITLE
Implement Seedlot Number Creation & Retrieval  on Frontend

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#475]
This task is to implement the integration between the frontend and the A Class Seedlot creation API.

It needs the following steps to be completed:

- [x] Adapt seedlot data on the frontend to be exactly like what's expected by the backend
- [x] Create and configure the API call
- [x] Check if the validation is working correctly
- [ ] Make sure all other pages that depends on seedlot number are working as expected

**Comment by mgaseta** [comment]
Moving this to blocked for now. The last step to finish this task is not working, some pages are dependent on seedlot information that the backend must provide after the seedlot number creation, so we need a new endpoint to fetch these information. It was working fine when using mocked data, but now we need to update it for "the real deal".

**Comment by mgaseta** [comment]
Depends on tasks #504 and #505

**Comment by craigyu** [comment]
Sorry I forgot about this ticket and completed it with #572 😅
