### ISSUE TITLE
Replace Keycloak by FAM for Authentication on FE

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#480]
## Description

Replace Keycloak by FAM in the front end.

⚠️ Note that FAM needs to know beforehand all the URLs for redirecting, and that's not possible with PR's deployments. That means we'll not be able to log in into DEV, for now.

## Acceptance Criteria

- [ ] App running smoothly locally and on TEST
- [ ] Login with IDIR working
- [ ] Login with Business BCeID working
- [ ] All tests passing
- [ ] No Keycloak dependency left in the project

**Comment by craigyu** [comment]
Done in #578
