### ISSUE TITLE
Add SPAR user's suggestion into Figma suggested feature board/tracker

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#487]
Task:

A SPAR user has reach out with a suggested improvement that they would find helpful. These suggestions need to be added to our Figma board so that we can included them in future discussions. 

1. In the Request Key Search screen, the user would like to be able to see the assigned nursery in the output table below:

![Image](https://user-images.githubusercontent.com/64149835/269055011-d4b9fccb-a2b5-4370-b108-e0efd7632c39.png)

2. in the seedling request nursery assignment screen (SPR202) the user would like to be able to see the number of seedlings or the number of grams of seed that is being grown at the nursery in the output table. 

![Image](https://user-images.githubusercontent.com/64149835/269056090-13f4c0f8-1b2f-4396-9ac4-5b73c4fff100.png)

Completion check list:

- [] items 1 and 2 are added to the lean inception workshop screen feature tracking board and other necessary places (Mural SPAR/CONSEP master board?)

**Comment by kevinginley** [comment]
This request was added to the [Lean Inception Developer's Workshop Figma board](https://www.figma.com/file/yXRFOeqLrnkHCHPu0JXRCj/SPAR---Lean-Inception-Workshop---Day-3?type=whiteboard&node-id=3-56918&t=laWeN0SwJsumBBps-0) and the [Lean Inception Results Data Synthesis feature list](https://bcgov.sharepoint.com/teams/07176/Shared%20Documents/General/UX%20Team/SPAR%20%26%20CONSEP%20(1)/Workshop%20-%20Lean%20Inception/SPAR%20Lean%20Inception%20Workshop%20Data%20Synthesis.xlsx?web=1).
