### ISSUE TITLE
Create API to fetch Client Search paginated screen

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#498]
Create an endpoint to fetch Forest Client with a pagination option.

Consider these fields on the search - client or agency:
- Name
- Acronym
- Number

Right now it is not possible to fetch data that contains the string the user is trying to filter.

Subtask of #447 
Depends on #525

**Comment by SLDonnelly** [comment]
Task: Sabina to ask team Alliance about timeline for getting # of results in API

**Comment by craigyu** [comment]
use query param, one endpoint for 3 categories
