### ISSUE TITLE
Create component structure for Client Search modal on FE

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#499]
Task:
Create the screen and table structure as shown in the Figma design file for the client search modal. https://www.figma.com/file/rFkWfep2NnJMdXku4GTXTN/Search-flows?type=design&node-id=429-431398&mode=design&t=4ZX4d5nhmnG68avD-4

Acceptance Criteria:
1. Implemented as per the design
2. Merged
3. Implemented in a way that it is ready to accept the backend endpoint

Subtask of #447

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/b9287793-dee6-4980-8003-46fb05a51817)
