### ISSUE TITLE
PATCH applicant and seedlot info

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#500]
Create an API to allow the first Seedlot registration screen to be edited. 

TBD: keep or clean all the data for that seedlot (on the table)?

Subtask of #463

**Comment by craigyu** [comment]
Use case:

![Image](https://github.com/bcgov/nr-spar/assets/25162561/c196ee61-6260-4db3-9c5e-fe04c9c22e3d)

Goal:
Create a PATCH endpoint that update an entry in the `seedlot` table, only the editable fields can be updated through this endpoint.

Criteria:
- Patch Endpoint is created -> PATCH: `/seedlots/{seedlotNumber}/applicant-and-seedlot-info
- Fields that can be updated on the seedlot table:
    - `applicant_email_address`
    - `to_be_registered_ind`
    - `bc_source_ind`
    - `seedlot_source_code`

**Comment by craigyu** [comment]
Lowering the points to a 2 due to simplicity
