### ISSUE TITLE
Spike to findout where is stored a user preference given its profile on WebADE

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#507]
Find out where (tables and columns) and how user's profile are stored inside WebADE.

**Comment by SLDonnelly** [comment]
@webgismd is there a WEBADE SME that we can reach out to for guidance?

**Comment by RMCampos** [comment]
### More info

- WebADE repo: https://apps.nrs.gov.bc.ca/int/stash/projects/INFRA/repos/webade-vm/browse?

Basically, all WebADE and ADAM SQL scripts can be found here: https://apps.nrs.gov.bc.ca/int/stash/projects/INFRA/repos/webade-vm/browse/flyway-webade/sql

**Comment by webgismd** [comment]
I am curious what user preferences you are looking for.. there are 17 roles in Webade for SPAR. Are you looking for that list or a list of users in each role? I wasn't sure if this is what is being asked?

**Comment by RMCampos** [comment]
@webgismd thanks for the question. We want to know:
- Roles, profiles and orgs of SPAR test users
- Default agency information (client number, acronym, location code) for the profiles and orgs

**Comment by RMCampos** [comment]
We now have access to files containing profile users count and organizations information. Let's call this done.
