### ISSUE TITLE
Screen edits

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#554]
During alpha testing, users have identified typos and language that could be made clearer. 

1) ~~Remove typo in the "my seedlots" table. There is a second "class" that is not needed.~~

![Image](https://github.com/bcgov/nr-spar/assets/64149835/f58c42aa-6b83-4682-a4b5-e6e5fbb9a501)

2) ~~Change button from "Complete registration" to "Edit seedlot form"~~

![Image](https://github.com/bcgov/nr-spar/assets/64149835/b7ea41d7-0a73-4f8e-8a54-798b83edbf15)

3) ~~Change banner from "Complete registration" to "Edit seedlot form"~~

![Image](https://github.com/bcgov/nr-spar/assets/64149835/5fe1f3fb-642c-4135-8919-1617ccc1e94a)

4) ~~Change the header from "Form Progress" to See where you are in the registration progress and move this section to the top.~~

![Image](https://github.com/bcgov/nr-spar/assets/64149835/3f171f15-2af7-43b4-9168-484048909e79)

5) ~~View only input components used for Applicant and seedlot information - you may need to ask Michelly for more clarification. There are notes for this in Figma~~

6) ~~Update language and buttons on the confirmation screen when a seedlot number has been generated:~~

![Image](https://github.com/bcgov/nr-spar/assets/64149835/7ccc1d7b-24d3-437c-8fec-9ccc0e8f1f96)

7) ~~Get rid of participants field in all screens.~~

![image](https://github.com/bcgov/nr-spar/assets/64149835/858ce6e5-c395-44d3-b56e-0be0ea5daa75)

8)  ~~Update Applicant agency screen:~~

- add a dash to the screen title to read "Create A-class seedlot"
- change header to "Email address"
- change helper text to "The email address may be used by the Tree Seed Centre to provide updates regarding registration
- remove helper text from species selection field

![Image](https://github.com/bcgov/nr-spar/assets/64149835/d24c1e4f-dcf4-49eb-acce-fe46aaadb916)

9) update Seedlot information section. 

- update field headers and add radio dial button for fields
-

![Image](https://github.com/bcgov/nr-spar/assets/64149835/1ace3cb8-08ea-4438-8e81-bab798baaa1c)

10) ~~Update applicant and seedlot information summary section.~~

- Change Applicant email address to "Email address"
- change field headers as shown below in screenshot:

![Image](https://github.com/bcgov/nr-spar/assets/64149835/b1cc84b6-137b-4cd8-ab5a-507f4c07d98d)

11) New ownership section. There is a new ownership card layout. The "Add owner" button will be at the bottom of the last card, instead of inside the first card. 

![image](https://github.com/bcgov/nr-spar/assets/99898407/6a4409b0-d43f-45e1-8724-8ca88dc79b01)

**Comment by SLDonnelly** [comment]
Hi @mmarsoleta, here is a list of changes. Can you confirm that I haven't missed anything? please feel free to edit and clarify too

**Comment by craigyu** [comment]
Only 9 and 11 remains to be done

**Comment by craigyu** [comment]
Done
