### ISSUE TITLE
Fix manifest.json file issue on frontend

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#562]
## Description

Go through the error message and understand why is that happening.

Screenshot from TEST:
![Image](https://github.com/bcgov/nr-spar/assets/2219519/1aedbeab-15aa-43b9-9b30-d7abc4812d23)

## Acceptance Criteria

No error messages and the `manifest.json` file served as json file.

**Comment by SLDonnelly** [comment]
Low priority
