### ISSUE TITLE
Bug: SMP mix template not downloading

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#568]
**Describe the Bug**
Under the "Calculation of SMP Mix" screen, the link to "Download calculation of SMP mix template", is not working. There is a new page that opens to this url: https://nr-spar-test-frontend.apps.silver.devops.gov.bc.ca/downloads/SMP_Mix_Volume_template.csv
However a template does not actually download.

![Image](https://github.com/bcgov/nr-spar/assets/64149835/a5a42c34-3735-4739-a15b-06c15a069354)

**Expected Behaviour**
A .csv template for SMP mix appears in your browser downloads

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Calculation of SMP Mix'
2. Click on 'Download calculation of SMP mix template link'
3. See blank url

**Screenshots**
See above

**Comment by SLDonnelly** [comment]
Update: The templates on the other tabs also do not work

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/651c7ec5-5326-433b-a066-6d641b3ba96b)


LOL it kinda worked but it downloads an html file

**Comment by SLDonnelly** [comment]
@craigyu haha, it's halfway there! Do you know why it flipped to html?

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/fec9caaa-5973-4af0-b50d-4c8e7e5d34d0)

I think it's something to do with react router

**Comment by mgaseta** [comment]
Tried changing how Caddy deals
