### ISSUE TITLE
[Staged] Integrate Seedlot Creation

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#572]
1. Users should be able to create a seedlot
2. Users should be directed to the Step 1 of the registration flow after clicking on "Continue Registration" button

**Comment by craigyu** [comment]
upping the story point to 3 due to the need to integrate with the said endpoint

**Comment by craigyu** [comment]
@SLDonnelly @RMCampos Wondering whether we should integrate the GET seedlot by number endpoint in this ticket as well, the registration flow and seedlot detail page will be broken if we don't

**Comment by RMCampos** [comment]
Are you refering to the integration for fetching all user seedlots? Do we need it for this task? I'd vote for having the mocked seedlot list for now, until we merge this one, and then tackle #573 in a separate PR. 

However.. If you feel the changes are quite related, go ahead! Let's do it.
