### ISSUE TITLE
Investigate P.T. numbers under an orchard

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#583]
During sprint review planning, Sabina discovered an issue where valid parent tree numbers are being displayed as invalid. 

How it works:
- front end retrieves a list of parent tree under an orchard
- if a user types in a p.t. number that is not present in that list, then it will show up as invalid.

The sql query for fetching all p.t. under an orchard:
```sql
 SELECT DISTINCT PT.PARENT_TREE_ID AS \"parentTreeId\",
              PT.PARENT_TREE_NUMBER AS \"parentTreeNumber\",
              O.ORCHARD_ID AS \"orchardId\", Q.SEED_PLAN_UNIT_ID AS \"spu\"
            FROM PARENT_TREE PT
            JOIN PARENT_TREE_ORCHARD PTO
              ON PTO.PARENT_TREE_ID = PT.PARENT_TREE_ID
            JOIN ORCHARD O
              ON O.ORCHARD_ID = PTO.ORCHARD_ID
            JOIN PARENT_TREE_GENETIC_QUALITY Q
              ON PT.PARENT_TREE_ID = Q.PARENT_TREE_ID
            WHERE O.ORCHARD_STAGE_CODE != 'RET' AND PT.VEGETATION_CODE = ?1
```

**Comment by thiagosanchezenc** [comment]
@craigyu @SLDonnelly could you please provide some examples of this behavior (parent tree number and orchard ID)?

**Comment by SLDonnelly** [comment]
Hello @thiagosanchezenc and @craigyu, during testing I was adding valid parent tree numbers into the SMP mix screen. I believe that the rules in the front end need to be updated. In the SMP mix screen, the front end should allow parent trees outside of the orchard, but parent tree numbers that have been registered and are the correct species
