### ISSUE TITLE
Add first run commands

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#60]
**Describe the task**
Once the repo is cloned, in case one need to work with any backend (in Java), maven will be required. Since `mvnw` is a wrapper e doesn't include a jar file, is required a command to retrieve this file (or manual copying from somewhere else).

I think would be good to add this notes on the CONTRIBUTING.md files.

This is the command: `mvn wrapper:wrapper`.

⚠️ Note that maven should be globally installed for this command work. A good option is to use `sdk man`, that is already covered in the contributing guide.

**Acceptance Criteria**
- [ ] All steps for running locally clearly described in the contributing guide.

**Additional context**
- No additional notes.

**Comment by DerekRoberts** [comment]
I think this is more or less covered by docker-compose.yml.  We can add to the docs if that's unclear.
