### ISSUE TITLE
Create Endpoints to store and retrieve Form json

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#604]
Create API to store each step (JSON). Related to #603

**Comment by craigyu** [comment]
2 endpoints:

PUT:
store the entire `allStepData` and `progressStatus` in a table called `seedlot_registration_a_class_save`

the end point should have the address: PUT '/seedlots/{seedlotNumber}/a-class-form-save`

GET:
Retrieve the seedlot form save row from the table `seedlot_registration_a_class_save`
the end point should have the address: GET '/seedlots/{seedlotNumber}/a-class-form-save`
