### ISSUE TITLE
Clickable Form Progress on the seedlot detail

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#613]
**Describe the task**
Make the progress bar clickable and correctly navigate to each step listed on it, regardless of the status of the step

**Acceptance Criteria**
- [ ] User should be redirected to the form page
- [ ] User should land on the step they clicked on  <- use query params? 

![Image](https://github.com/bcgov/nr-spar/assets/25162561/4fe9bfb8-9b6f-464b-9f03-2c02774457bb)

**Comment by SLDonnelly** [comment]
scope: make the steps clickable and redirect
