### ISSUE TITLE
Date input width bug

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#620]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/e7bcfdf6-1399-43da-b24a-be86d66aeccd)

The date inputs on the registration form aren't displayed with full width.
The cause of this issue is unknown.
A potential fix is ready, and Matheus is investigating the root cause.

Credit to Matheus for finding this bug!

**Comment by mgaseta** [comment]
The component changed on a new version of the Carbon library, even though we didn't updated the library on our project... Probably it was backpropagated to older versions (my best shot).
