### ISSUE TITLE
Write invitation for TSC user journey validation workshops

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#705]

**Comment by kevinginley** [comment]
Here's what I've come up with so far. I didn't use the term "workshop" because I thought that may sound like more time/effort than would actually be required for participants.

Subject line: CONSEP workflow validation session: Cone and Seed Processing
Subject line: CONSEP workflow validation session: Quality Assurance
Subject line: CONSEP workflow validation session: Inventory Management

**Message body:**
Thanks once again for your time and input walking us through how you use CONSEP for day-to-day activities.

We’ve taken what we heard during our CONSEP user interviews and mapped out different user journeys based on job type and associated workflows.

The next step is to schedule a brief review session to share what we mapped out, and confirm whether we captured all the relevant steps and information, or whether further details could be added or clarified.

This validation step is to make sure we don’t miss any key features or functionalities as we design new CONSEP screens.

Thank you for your participation, and feel free to suggest an alternative time if this timeslot won’t work.

**Comment by SLDonnelly** [comment]
@kevinginley good call not using the term workshop - I agree with you!

The invitation looks great :) Will you and @mmarsoleta want to do this with the different user groups between January 10th and January 19th? This would give you a couple of days to prepare after getting back from your holidays
