### ISSUE TITLE
Create and Integrate GET Interim Facility Types Endpoint

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#718]
Create a GET Interim Facility Code endpoint in **Oracle Service** to fetch data in the `INTERM_FACILITY_CODE` table :
![Image](https://github.com/bcgov/nr-spar/assets/25162561/288827e9-bf33-4e8d-8ec9-b28d163425fb) 

Integrate this endpoint to to step 3 of the registration flow. it is currently hard coded, the front end should fetch the data then put the data into list of `MultiOptionsObj`, then dynamically map the radio buttons. 

Use the `select` option in `useQuery` to transform the data into `MultiOptionsObj`, instead of doing that inside of the api call function. 

![Image](https://github.com/bcgov/nr-spar/assets/25162561/6f90bff6-4a8e-49d0-b224-9186ca63ffc6)

**Comment by mgaseta** [comment]
**Update**

Had some problems while running forest-client api requests and local oracle-api at the same time, to run and test oracle-api locally we need to be connected to the VPN, but forest-client api requests will not work while connected to the VPN.

To avoid this issue, I created PR #733 and I'll test the changes using the oracle-api dev deployment created by the github actions, so please, don't review the changes yet. I'll update this task and send direct message to the team when it's ready for review.

Thanks!

**Comment by mgaseta** [comment]
Finished testing, it's officially open for review! #733
