### ISSUE TITLE
Integrate PUT seedlot form progress endpoint on front end

### ISSUE THREAD

**Issue by Sarah-n-adams** [bcgov/nr-spar#720]
Acceptance Criteria:

Basic: Save progress on next or back click
Bonus: Autosave after inactivity or x amount of edit

**Comment by mgaseta** [comment]
Depends on #604

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/b1b01904-b105-41fb-bd6c-3aca4f1acf64)

**Comment by craigyu** [comment]
bonus achieved

**Comment by craigyu** [comment]
+1 point for bonus feature
