### ISSUE TITLE
Client Search Look Up Assist User Journey

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#729]
As a SPAR user registering a seedlot, I want a client search/look up assist so that I can find the correct forest client agency in case I don't remember/know the exact client acronym, client number or the exact company name. 

### Acceptance Criteria

1. If I enter a valid client acronym, a list of forest clients with the exact acronym or ones that contain a portion of the searched acronym will be populated in an output table
![image](https://github.com/bcgov/nr-spar/assets/64149835/e144b0b2-2949-4ea3-a02a-13950104b02b)
 
2. If I enter a valid forest client number, a list of forest clients with the exact number or ones that contain a portion of the searched number will be populated in an output table

3. If I enter a valid client name, a list of forest clients with the exact name or ones that contain a portion of the searched name will be populated in an output table

4. When I select a row in the output table, the data will be applied to the field that I was filling in (collection agency, storage agency, extraction agency, seedlot owner)

Also, here are a few points/constraints that need to be needed:

1. It is mandatory to enter either a client name, number or acronym; 
2. The search will be triggered when hitting the "search" primary button;
3. This pictogram shown in the design will be used for the empty state/no parameters given (https://www.figma.com/file/rFkWfep2NnJMdXku4GTXTN/Search-flows?type=design&node-id=429-434914&mode=design&t=0CP22sMGOI6tc2zO-4) 

### Resources:

* Figma design: https://www.figma.com/file/rFkWfep2NnJMdXku4GTXTN/Search-flows?type=design&node-id=429-444392&mode=design&t=0CP22sMGOI6tc2zO-4

### Notes

Business rules, notes are provided in the Figma file here: https://www.figma.com/file/rFkWfep2NnJMdXku4GTXTN/Search-flows?type=design&node-id=506-419223&mode=design&t=0CP22sMGOI6tc2zO-4

**Comment by craigyu** [comment]
moved to milestone
