### ISSUE TITLE
Update Figma design for Client Modal

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#736]
**Describe the task**
During backlog refinement, proposed changes to the client modal design were discussed:

1) Client type is not longer needed
2) The user must specify what kind of data they are searching for (acronym, client number, client name)

**Acceptance Criteria**
- [ ] Items 1 and 2 are addressed
- [ ] Changes are shown in the Figma design
- [ ] Decision/rational is documented

**Comment by mmarsoleta** [comment]
@SLDonnelly , between client name, acronym and number, what would be the most used parameter again? The dropdown menu option will use this most used parameter already selected by default.

**Comment by SLDonnelly** [comment]
@mmarsoleta for searching, I would say the client name would be the first parameter used, then acronym and number
