### ISSUE TITLE
User feedback - changes to screen 4 and 5

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#737]
During user testing of the A class registration screens, users provided the following feedback:

1. The radio dial button on the male gametic contribution was confusing because the female gametypic contribution was a drop down. They would prefer that both fields are a drop down.
2. For some users it took them a bit of time to find the buttons on the right hand side of the screen. Andrea K. would like buttons to be located on the left hand side for consistency
3. Users found that the current tab style did not stick out, and they scrolled passed it when looking for the SMP and pollen contamination screens. 

Criteria:
1) Change the male gametic contribution methodology field (screen 4) from a radio dial button to a drop down
2) Change the position of buttons (data upload tool) from the right to the left
3) Change the style of the tabs in screen 5 to a more style that has more contrast for users.

**Comment by mgaseta** [comment]
Closing it, since it's in the done column.
