### ISSUE TITLE
Change routes settings on FE

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#748]
Currently we are setting all paths directly on our `App.tsx` file, which is turning out to be a huge file and this is not a nice practice.

So, the objective of this task is to make a quick reconstruction on our routes and how we deal with them, following the best practices for the `react-router` library.

This is an example of how it should look like: https://semaphoreci.com/blog/routing-layer-react

**Comment by RMCampos** [comment]
Blocked due to FAM changes. Some discussion is needed to find out how to solve this issue.

**Comment by mgaseta** [comment]
Unblocked! 

Not sure what fixed it, but it is not happening anymore.
