### ISSUE TITLE
Frontend Responsiveness (Seedlot dashboard)

### ISSUE THREAD

**Issue by ArthurEncr** [bcgov/nr-spar#769]
Sub-task from [#193](https://github.com/bcgov/nr-spar/issues/193)
Responsiveness a bit broken after recent changes, after some tests some issues were spotted at this screen:

MEDIUM (672px): 
- [x] Should have 2 cards per line
![Image](https://github.com/bcgov/nr-spar/assets/117835311/6cec0846-703c-4284-be87-5997a8ea39ad)

SMALL (320px): 
- [ ] Cards should turn into smaller buttons
![Image](https://github.com/bcgov/nr-spar/assets/117835311/fb9e31e1-873f-4648-b0f1-c9ddae3a7c49)

**Comment by ArthurEncr** [comment]
branch with fixes: fix/769-frontend-responsiveness-seedlot-dashboard

**Comment by craigyu** [comment]
![Image](https://github.com/bcgov/nr-spar/assets/25162561/9e918f1f-1229-42ad-a432-4650764e2851)

This clearly isn't going to work as the inner width won't be updated. this should be done with the hook we created. I'm deleting this branch
