### ISSUE TITLE
Frontend Responsiveness (My seedlots)

### ISSUE THREAD

**Issue by ArthurEncr** [bcgov/nr-spar#772]
Sub-task from [#193](https://github.com/bcgov/nr-spar/issues/193)
Responsiveness a bit broken after recent changes, after some tests some issues were spotted at this screen:

MEDIUM (672px):
   - [ ]  Can't view the table (it's cut in half)
![Image](https://github.com/bcgov/nr-spar/assets/117835311/aca4edb0-9222-45e1-91c6-68932fd6940e)

SMALL (320px):
  -  [ ]  Can't view the table (it's cut in half)
   - [ ]  Fix paddings (button and description too close)
![Image](https://github.com/bcgov/nr-spar/assets/117835311/079e6e7a-ad0c-4cd2-a29b-391fcd3b3e6c)

**Comment by craigyu** [comment]
>  Can't view the table (it's cut in half) 

^ this isn't an issue since user can scroll to view
