### ISSUE TITLE
Frontend Responsiveness (Seedlot details)

### ISSUE THREAD

**Issue by ArthurEncr** [bcgov/nr-spar#774]
Sub-task from [#193](https://github.com/bcgov/nr-spar/issues/193)
Responsiveness a bit broken after recent changes, after some tests some issues were spotted at this screen:

MEDIUM (672px):
- [ ] All sections are not being shown in full
- [ ] No edit button

![Image](https://github.com/bcgov/nr-spar/assets/117835311/5a0d32f4-d70c-48f8-b86e-aa96f36d8494)

SMALL (320px):
- [ ] All sections are not being shown in full
- [ ] No edit button
- [ ] Breadcrumb should be at same line (disable line breaking)

![Image](https://github.com/bcgov/nr-spar/assets/117835311/62ac4fc6-4674-4035-bae0-978d5369337e)

**Comment by ArthurEncr** [comment]
Also, the form steps should be in vertical mode (the section should change too)

**Comment by craigyu** [comment]
i don't understand what "No edit button" is referring to, skipping it
