### ISSUE TITLE
SPIKE: review package file to determine SMP calculation

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#779]
**Describe the task**
We need to build the calculation for mean degrees latitude and longitude in the SMP success on parent screen. We need to determine if the current documentation gives us all the information needed to develop the SMP lat long and elevation means. For example, does all the data come from oracle or postgres??

 A spike will need to be done to review the package files in the legacy database and the current documentation so that the calculation can be replicated in new SPAR. SMP package file from the legacy application is attached. Link to the SMP analysis in Confluence is also linked below. 

https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/SPR_001A_SMP_CALCULATION+Package+Analysis

![Image](https://github.com/bcgov/nr-spar/assets/64149835/b3d79837-ed40-4ad0-9ec0-f5a045d27b33)

**Acceptance Criteria**
- [x] Spike of package and calculations
- [x] documented in Confluence

[CREATE OR REPLACE PACKAGE spr_001a_smp_calculation AS.docx](https://github.com/bcgov/nr-spar/files/13953273/CREATE.OR.REPLACE.PACKAGE.spr_001a_smp_calculation.AS.docx)

**Comment by RMCampos** [comment]
SMP calculations:

### First loop through list to get total amount of material and # of pt outside of seedlot.
```java
var smpMixList = find All smp_mix records for that seedlot number;

for (SmpMix smpMix : smpMixList) {
  if (smpMix.amount_of_material is not null) {
    v_total_amount_of_material += smpMix.amount_of_material;
  }
  
  // checks if the parent tree is inside the orchard
  select seedlot_number from seedlot_parent_tree where seedlot_number = main_seedlot_number and parent_tree_id = smpMix.parent_tree_id;
  if (seedlot_number is not null) {
    v_num_parents_from_outside += 1;
  }
}
```

### Second loop through list to calculate proportion and weight values.
```java
for (SmpMix smpMix : smpMixList) {
  /* calculate the proportion 
  * PS: we don't need that. We're doing this calculation in the FE
  */
  if (smpMix.amount_of_material is not null) {
    smpMix.proportion = smpMix.amount_of_material / v_total_amount_of_material;
  }
  
  /* weighted for each trait */
  fetch the smp_mix_gen_qlty record
  var weighted_bv_AD = smpMix.proportion * smp_mix_gen_qlty_ad.genetic_quality_value;
  // repeat for DFS, DFU, DFW, etc..
  
  /* mean elevation */
  var weighted_elevation = smpMix.proportion * smpMix.elevation;
  var v_coll_lat = (p_pt(i).latitude_degrees*60) + p_pt(i).latitude_minutes + (p_pt(i).latitude_seconds/60);
  var v_coll_long = (p_pt(i).longitude_degrees*60) + p_pt(i).longitude_minutes + (p_pt(i).longitude_seconds/60);
  
  p_pt(i).weighted_latitude = p_pt(i).proportion * NVL(v_coll_lat, 0);
  p_pt(i).weighted_longitude = p_pt(i).proportion * NVL(v_coll_long, 0);
  
  /* sums all weighted values, for each trait */
  v_sum_wtd_bv_AD += weighted_bv_AD;
  
  /* set smp mix calculated values. For each traita */
  p_smp_mix_bv_AD = v_sum_wtd_bv_AD;

  /* 
  * !! the packages doesn't save the calculated. But I think we need to do it.
  * saves the calculation!
  */
}
```

**Comment by RMCampos** [comment]
Confluence page: https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/SMP+Calculation

**Comment by RMCampos** [comment]
Finished with the confluence document page.
