### ISSUE TITLE
Area of Use (SPZ) calculation

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#788]
**As a** *business area members* **I want** *Seed Planning Zones  to continue to be calculated**So That** * we can continue to see the Geographic Based Seed Transfer of Seedlots*

[Tech Specs - Area of Use Information.txt](https://github.com/bcgov/nr-spar/files/13982812/Tech.Specs.-.Area.of.Use.Information.txt)

[A class SPUand SPZ rules.pdf](https://github.com/bcgov/nr-spar/files/13992354/A.class.SPUand.SPZ.rules.pdf)

**Additional Contex

- In the legacy system, this is a calculation done by the application
- The output of the calculation will be saved to the post gres table. The ETL pipeline will then sync this data to the corresponding Oracle table where the legacy application screens will be able to pick up the data needed. 

**Acceptance Criteria**

- [ ] When a new seedlot is submitted, the calculation is run, then is it saved to the PostGres DB.
- [ ] When the ETL pipeline runs, the Area of Use data is synced to the correct tables and columns in DBP01 where legacy SPAR screens can pick up the data

### Subtasks required to close this one
- 1 of 4 - https://github.com/bcgov/nr-spar/issues/830
- 2 of 4 - https://github.com/bcgov/nr-spar/issues/795
- 3 of 4 - https://github.com/bcgov/nr-spar/issues/794
- 4 of 4 - https://github.com/bcgov/nr-spar/issues/816

**Comment by RMCampos** [comment]
Possible tasks:

- Create task to run the calculations once the seedlot is submitted
- Create API to fetch SPZ information to a given Seedlot number
