### ISSUE TITLE
A Class Seedlot Registration UI changes

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#803]
**Describe the task**

During user testing and development, potential changes to the UI were identified. 

Part 1.  Background: When a user does not enter pollen count data, they may not get a score for a particular trait due to the way that we are now accurately calculating parental contribution in the new system. This might catch some users off guard as they were able to get away with this in the old system. 
 
Problem: We need a way of informing the user as to why their seedlot is not getting a score.

Solution: Provide a message to the user (tool tip, banner etc) that states: To get a genetic worth rating, the parental contribution of the tested parent trees must represent >70% of the total parental contribution of all parent trees (click here to see the Chief Forester's standards)

Part 2. Background: When a user submits a seedlot and the status changes to pending, the form needs to be locked to prevent editing by the user. The functionality of the Form review section was discussed. The intent of the review form  was to be used when a seedlot was shared with another SPAR users. This feature will not be included in MMP1. During discussions, we decided to exclude the form review for the time being. 

Problem: What is the expected action when a seedlot is submitted and editing is locked?

Solution: update figma file to exclude seedlot form review section and update buttons so that when in pending status the edit button is visible and when in submitted status, the edit buttons are hidden and only view is allowed.

**Acceptance Criteria**
- [ ] Solution reviewed by Michelly, Kevin, Sabina and Craig
- Changes reflected in Figma
- [ ] what is the output of this task? - updated Figma design

**Comment by mmarsoleta** [comment]
Reviewed by sabina on ticket "Interface adjustments for A-class registration and Seedlot details pages
[#827](https://github.com/bcgov/nr-spar/issues/827)"
