### ISSUE TITLE
Update Seedlot GET endpoint to fetch parent tree information

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#806]
This taks aims to upgrade the current endpoint for getting Seedlot information (based on the seedlot number), to fetch the parent tree information of the Seedlot too.

![Image](https://github.com/bcgov/nr-spar/assets/105936322/64f0136d-fede-483f-9375-338f78af4ca7)

**Comment by mgaseta** [comment]
Upgrading to 5 points due to the new founds regarding seedlot's parent trees tables.
@RMCampos wrote a very nice document regarding them.

**Comment by craigyu** [comment]
Rolled over from Sprint 24

**Comment by mgaseta** [comment]
This is blocked due to task #844

**Comment by mgaseta** [comment]
Now, blocked due task #866.

**Comment by mgaseta** [comment]
Rolled over from sprint 25.
