### ISSUE TITLE
Secrets Management Documentations - for Data Engineer

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#807]
**As a** *PO* **I want** *Security Documentation* **So That** *Security, Threat and Risk Assessment requirements are met.*

Task:

The STRA requires documentation regarding Secrets Management. Please use guide prodivided below:

**Secrets Management**

    -[ ] Secrets registry, a list of secrets your team use
    -[ ] Secret rotation procedure, can use this [template](https://apps.nrs.gov.bc.ca/int/confluence/x/toTmCg) to create your own

**Acceptance Criteria**
- [ ] Documentation that has privacy concerns is documented in Confluence and linked to Github wiki

**Definition of Done**
- [ ] Documentation drafted
- [ ] Documentation reviewed
- [ ] Documentation published and appropriately linked

**Comment by marcionemec-daitan** [comment]
Documentation available at:

https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Data+Sync+Engine+-+Secrets

**Comment by mgaseta** [comment]
Closing it, since it's in the done column and documentation is available.
