### ISSUE TITLE
Create Review Seedlot Submissions button  

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#814]
**Describe the task**

Prior to releasing into Production, the legacy application will need to be updated to turn off the A class registration capability and redirect users to the correct page. One of the redirections needed is for TSC Admin who are responsible for pulling up seedlot registration submissions, reviewing them, approving them or returning them back to pending for the user. 

**Acceptance Criteria**
- [ ] Redirect button built in old application
- [ ] Button redirects users to new SPAR

**Comment by RMCampos** [comment]
In orfer of being able to properly estimate this task, we need to finish two spikes. They are:

- #853 
- #853

**Comment by SLDonnelly** [comment]
This ticket is no longer needed as we have changed direction. A redirect button was too complicated to develop in the old system
