### ISSUE TITLE
Development of Seedlot Review step 1 - applicant and seedlot information

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#817]
Describe the task:

Create FE of Seedlot Review, Step 1 (applicant information) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284788&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/64149835/85c4518d-0ea6-461f-9685-8e2ea4f31ec4)

Acceptance Criteria
- [ ] Developed as per Figma
- [ ] relevant documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by craigyu** [comment]
upped to a 5 point, quite a bit of work was necessitated
