### ISSUE TITLE
Interface adjustments for A-class registration and Seedlot details pages

### ISSUE THREAD

**Issue by mmarsoleta** [bcgov/nr-spar#827]
Some interface changes were requested by PO and/or key users. Changes done in the design file should match the changes in code as well.

1. Changes inside "Parent tree and SMP" step for A-class seedlot registration
2. Changes inside seedlot details page
3. Global changes for A-class seedlot registration

note: additional changes on the comment section (adjustments requested during review)

**Changes inside "Parent tree and SMP" step for A-class seedlot registration**

> 
> **1.1 - Tab style**
> _Was:_ inline
> _Change to:_ container style
> _Reference:_[new tab style on figma](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7102-82629&mode=design&t=4Zh4tmYPpokHI2RA-4)
>_Requested by:_ user feedback
>_Goal:_ give tabs more visibility 
>
> ![Image](https://github.com/bcgov/nr-spar/assets/99898407/40d52cdf-025d-4582-a27c-fbf728882e4c)
>

>
>**1.2 - New page structure**
>_Was:_ content over background
>_Change to:_ table, summary and genetic worth over a container component. background color changed to layer-01 and a border was added to card/table. 
>_Reference:_ [new page layout](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7102-82612&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ user feedback
>_Goal:_ give tabs more visibility - background and structure change due to container tab style
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/6e5e323d-ce39-4ccf-8bef-0b0fbd917069)
>

>
>**1.3 - Summary section** 
>_Was:_ over background
>_Change to:_ a separate card section 
>_Reference:_ [new summary](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7107-114794&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ 
>_Goal:_ 
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/cb983311-f035-490e-8472-9debc2f3e109)
>

>
>**1.4 - Genetic worth and effective population size**
>_Was:_ over background, genetic worth and effective population size were separated, calculate genetic worth and effective population size was bellow both sections
>_Change to:_ genetic worth and effective population size are under the same card section now, the button to calculate the genetic worth and effective population size is incorporated to the card. 
>_Reference:_ [new genetic worth and effective population section](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7107-114804&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ 
>_Goal:_ improve usability and make the action to calculate results more intuitive
>
> ![Image](https://github.com/bcgov/nr-spar/assets/99898407/04a3cdc2-e0e2-4a8b-8bf9-56282e003fe6)
>

>
>**1.5 - Calculate genetic worth and effective population size**
>_Was:_ genetic worth and percent of tested parent tree contribution, and effective population size and diversity fields were always visible
>_Change to:_ Typography style and hierarchy are different. Label and title changed to "tested parent tree contribution". Results will only show if button is triggered, then button's label will change to "Recalculate". 
>_Reference:_ [new calculated results section](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7136-125464&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ 
>_Goal:_ improve usability and make the action to calculate results more intuitive
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/626e71a3-40ce-4fb4-ba08-61013314d6dc)
>

>
>**1.6 - New alert for missing parental contribution**
>_Was:_ --
>_Change to:_ New alert condition for when there is not enough parental contribution to calculate specific genetic trait (it should have at least 70% for system to be able to show the genetic worth results for each trait. Show banner with warning message. Change input color to red if value is below 70% and show warning icon besides it.
>_Reference:_ [new parental contribution alert](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7136-125495&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ Business rule update
>_Goal:_ let users know why there is no genetic worth results for a specific genetic trait
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/b6c13347-cb58-4dd9-bac7-512d8fa6c5ed)
>

>
>**1.7 - Table style**
>_Was:_ using table style according to DS
>_Change to:_ new table style should be applied. Zebra style is using layer-01 color. Action buttons inside table's header are aligned to the left. Using ghost buttons with label, not only icon. "Clear data table" is outside the "more actions" and visible on screen. Table's background changed to layer-02 (white).  
>_Reference:_[new table style](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7102-82637&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ Design leaders
>_Goal:_ standardize table across applications  
>PS: maybe this is a DS task - table's styles will be updated across applications and new pattern was defined by designer lead.(e.g. all tables will have zebra style, all tables should have buttons aligned to left, all tables should have label + icon if there is enough space, etc.)
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/0a3fb891-739e-4b83-83a3-4aa7df0f3f7f)
>

>
>**1.8 - Instruction at the top**
>_Was:_ --
>_Change to:_ add accordion component to display instruction on how to fill up/edit/upload file to table. Instructions should guide users on how to proceed with table fill. Also remove the info banner.
>_Reference:_ [new instructions section](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7102-82612&mode=design&t=ppkVQza04Acn57Nw-4)
>_Requested by:_ suggested by design leaders and PO
>_Goal:_ give more clarity to users
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/00d39490-9feb-4187-b483-e21340830b41)
>

**Changes inside seedlot details page**

>
>**2.1 - Remove review form section**
>_Was:_ There was a review form section 
>_Change to:_ Remove review form section from seedlot details page for every user besides TSC ADM
>_Reference:_ [seedlot details](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7168-234388&mode=design&t=6RjwywSPSK02OelX-4)
>_Requested:_ MVP 1 
>_Goal:_ make the screen easier to build and less repetitive. 
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/b397f2cc-cd05-4fc6-b9d9-81ab8a1b1cae)
>

>
>**2.2 - Can't edit when submitted or approved status**
>_Was:_ There was a "edit seedlot" and "edit applicant" button for every seedlot status 
>_Change to:_ Users should not be able to edit the form or the applicant information when the seedlot is submitted or approved. Remove the "edit applicant" button from "Check your applicant and seedlot information" section. Change the "edit seedlot form" button's label to "View seedlot form", inside the "see where you are in the registration process" and at the combo-button action.
>_Reference:_ [seedlot details - submitted and approved status](https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7168-238200&mode=design&t=6RjwywSPSK02OelX-4)
>_Requested:_ business rule
>_Goal:_ make the interface follow the determined business rule. 
>
>![Image](https://github.com/bcgov/nr-spar/assets/99898407/3cce8d36-4639-4bd6-a1cc-e901ba4b636b)
>

**Global changes for A-class seedlot registration**

>
>**3.1 - Title change**
>_Was:_ Seedlot registration
>_Change to:_ Registration for seedlot ##### [number]
>_Reference:_ [new title]
>_Requested:_ user feedback
>_Goal:_ increase seedlot number's legibility by putting the number on the title
>
> ![Image](https://github.com/bcgov/nr-spar/assets/99898407/ca741879-f23a-4b32-8d19-08768e34bcd7)
>

>
>**3.2 - subtitle change**
>_Was:_ Seedlot ##### [number]
>_Change to:_ display only "smartsave" toggletip (all changes saved)
>_Reference:_ [new subtitle]
>_Requested:_ user feedback
>_Goal:_ increase seedlot number's legibility by putting the number on the title
>
> ![Image](https://github.com/bcgov/nr-spar/assets/99898407/eb0c2020-b7d2-4856-8a97-59681cd4d750)
>

**Comment by mmarsoleta** [comment]
@SLDonnelly @craigyu @kevinginley  - Here we have all changes done to the registration form and seedlot details page as requested. It's ready for review :)

**Comment by SLDonnelly** [comment]
Hello @mmarsoleta! This looks good :) I just have a few small edits:  

1. Get ride of "estimative the" and change to "Enter the cone and pollen count (required)"

![Image](https://github.com/bcgov/nr-spar/assets/64149835/7e5d36b1-4c2c-4cff-871f-b404a8fe37f5)

2. I wonder if it is worth removing a couple of the subheadings? For example, with the button this one might be redundant and removing it would clear up the form:

![Image](https://github.com/bcgov/nr-spar/assets/64149835/3ec2689b-2b7b-4204-a855-9dec082f23e0)

@kevinginley and @mmarsoleta let me know if you disagree, otherwise nothing else from me :)
