### ISSUE TITLE
Inefficient Regular Expression Complexity in nth-check

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#83]
Contents require login.

https://github.com/bcgov/nr-spar/security/dependabot/1
https://github.com/bcgov/nr-spar/security/code-scanning/1

**Comment by RMCampos** [comment]
Issues:

- [Inefficient Regular Expression Complexity in nth-check](https://github.com/bcgov/nr-spar/security/dependabot/1) -> Closed with https://github.com/bcgov/nr-spar/pull/409
- [Inefficient regular expression complexity](https://github.com/bcgov/nr-spar/security/code-scanning/1) -> Also closed with https://github.com/bcgov/nr-spar/pull/409
