### ISSUE TITLE
Add SPZ columns in the seedlot_seed_plan_zone table

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#830]
Update existing table `seedlot_seed_plan_zone` on `Postgres-api` with missing columns for the Seed Plan Zone information.

### What to do
- Create a SQL migration;
- Update the existing Java entity class with new properties;

Something like:
```SQL
alter table spar.seedlot_seed_plan_zone
  add seed_plan_zone_id smallint,
  add genetic_class_code varchar(1);

comment on column spar.seedlot_seed_plan_zone.seed_plan_zone_id is 'A unique identifier for a combination of Seed Plan Zone Code, Genetic Class and Vegetation Code';
comment on column spar.seedlot_seed_plan_zone.genetic_class_code is 'A code describing various Genetic Classes.';
```

### Position
- Subtask 1 of 4 of https://github.com/bcgov/nr-spar/issues/788

### Dependencies
- None

**Comment by craigyu** [comment]
will make it so that `genetic_class_code` is an FK referencing the `genetic_class_list` table

**Comment by craigyu** [comment]
will keep the `genetic_class_code` as a varchar type to make it consistent with `genetic_class_list`

**Comment by craigyu** [comment]
this was more like 0.5 point
