### ISSUE TITLE
Development of Seedlot Review step 2 - Collection

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#832]
Describe the task:

Create FE of Seedlot Review, Step 2 (Collection) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284808&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/3cd372f1-0b4a-4392-88c7-4346494a13f0)

Acceptance Criteria
- [ ] Developed as per Figma
- [ ] relevant documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added

**Comment by craigyu** [comment]
upped from 2 to 3
