### ISSUE TITLE
Development of Seedlot Review step 5 - Interim Storage

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#833]
Describe the task:

Create FE of Seedlot Review, Step 5 (interim storage) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284935&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/846e1875-6c58-4904-a7fb-323af3d8201e)

Acceptance Criteria
- [ ] Developed as per Figma
- [ ] relevant architecture documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by craigyu** [comment]
moved from sprint 28 -> 29
