### ISSUE TITLE
Development of Seedlot Review step 6 - Orchard

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#834]
**Describe the task**
Create FE of Seedlot Review Step 6 (Orchard) and integrate endpoints as you go along. 

Figma design here:  https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284956&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/3cf7446b-a5a2-4f0b-8c0a-b4498b8b19a7)

**Acceptance Criteria**
- [ ] Developed as per Figma
- [ ] relevant architecture documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added
