### ISSUE TITLE
Development of Seedlot Review Step 7 - Parent Tree Contribution

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#835]
**Describe the task**
Create FE of Seedlot Review Step 7 (Parent Tree Contribution) and integrate endpoints as you go along. 

Figma design here:  https://www.figma.com/design/ROgZJQezb1DDG4AvEgjtpw/TSC-Reviewer---Seedlot-Registration?node-id=4435-269093&t=120s8kA8RWOIbOuR-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/d6111ec9-8f43-41b5-bbe4-deb0b145141c)

**Acceptance Criteria**
- [ ] Developed as per Figma
- [ ] relevant documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added

**Comment by mgaseta** [comment]
Blocked due necessary changes on how to deal with cone and pollen count changes, since these changes affects other sections.
