### ISSUE TITLE
Development of Seedlot Review Step 8 - Extraction and Storage

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#836]
**Describe the task**
Create FE of Seedlot Review Step 6 (Extraction Agency and Storage) and integrate existing endpoints as you go along. 

Figma design here:  https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284978&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/a8dc2ba9-fc79-4153-a9ce-2dea58d3b20a)

**Acceptance Criteria**
- [ ] Developed as per Figma
- [ ] relevant architecture documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added
