### ISSUE TITLE
Client Search improvements

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#837]
The client search API will timeout when searching for a keyword that has too many matching results, e.g. `thomas`.
The "full name" column also of only displays the last name of a client, this is fine for an entity but not good for individuals.

Acceptance Criteria:
1. ~~Increase the timeout of the search endpoint~~
2. Sorting works as intended  ✅
3. format client name in the format of `[lastname], [firstname]`  ✅

**Comment by craigyu** [comment]
Bringing in Derek to help us determine the cause of the timeout issue, it does not occur on local environment so it's likely something to do with openshift.

**Comment by SLDonnelly** [comment]
Hi @DerekRoberts! Any chance you've determined the cause of the timeout issue?

**Comment by DerekRoberts** [comment]
Hi @SLDonnelly!  Unfortunately not, because we have to fix other issues before troubleshooting this.  Mostly around not having working PR deployment environments.

**Comment by SLDonnelly** [comment]
rolled over from sprint 25 to 26

**Comment by craigyu** [comment]
rolled over from sprint 26 to 27
