### ISSUE TITLE
Vault Secrets Management

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#840]
SPAR currently lacks a way to securely store secrets in a way that can be accessed by team members. 
Our [Secure Design & Coding Practices](https://apps.nrs.gov.bc.ca/int/confluence/pages/viewpage.action?pageId=182879438) mandates that we implement and follow this practice.

This task will accomplish this by following these documents:
- [Vault secrets management](https://docs.developer.gov.bc.ca/vault-secrets-management-service/#how-to-request-access)
- [Vault getting started guide](https://docs.developer.gov.bc.ca/vault-getting-started-guide/)

**Comment by craigyu** [comment]
Secrets added to vault ->  [how to access secrets](https://github.com/bcgov/nr-spar/wiki/Secrets-list#access-secrets-value)\

Decreased points from 2 to 1.

**Comment by RMCampos** [comment]
As for secrets on Vault, only team leads can have access to. That means we may not use this option (Vault) for safely sharing projects secrets.

cc: @SLDonnelly @craigyu
