### ISSUE TITLE
Parent tree table not rendering correctly for certain orchards

### ISSUE THREAD

**Issue by mgaseta** [bcgov/nr-spar#842]
**Issue**
When registering a new A-Class seedlot, after selecting an orchard on step 4 and continuing the registration to step 5, the parent table is not correctly rendered.

![Image](https://github.com/bcgov/nr-spar/assets/105936322/42bd1080-a462-47d7-941e-6e6671d3f515)

**Steps to reproduce**
1. Create a new A-Class Seedlot
2. Register the seedlot
3. On step 4, select an orchard
4. Go to step 5, the parent table will not render any value

**Additional Comments**
This does not happen for every orchard, use the following seedlot data to reproduce:
Seedlot species: `DR - Red alder`
Select orchard: `410 - YELLOWPOINT - S - DEV`

Also, this error pops on the console:

![Image](https://github.com/bcgov/nr-spar/assets/105936322/e0689470-b449-442e-aefe-ad4eed552d22)

**Comment by craigyu** [comment]
Thanks Matheus for this well written issue!

**Comment by SLDonnelly** [comment]
@mgaseta @craigyu orchard 410 doesn't have any parent trees listed for it, therefore the fact that the parent tree list is not being populated makes sense :) Users will need to the "parent tree orchard" screen in the old system to add or update parent trees that are in their orchard

**Comment by mgaseta** [comment]
Thanks @SLDonnelly, so we should show the user a message explaining that, right? Any suggestion for the message or can @craigyu get creative?

**Comment by SLDonnelly** [comment]
We have the reminder above reminding users to update the parent tree contribution 
![image](https://github.com/bcgov/nr-spar/assets/64149835/83961b4e-009f-4cd5-905a-1e3afdfc7b0d)
@kevinginley @mmarsoleta do you have any thoughts of what, how to display a message to users where are there aren't and parent trees linked with a particular orchard?

**Comment by mmarsoleta** [comment]
> We have the reminder above reminding users to update the parent tree contribution ![image](https://private-user-images.githubusercontent.com/64149835/303465402-83961b4e-009f-4cd5-905a-1e3afdfc7b0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MjcwNDAsIm5iZiI6MTcwNzQyNjc0MCwicGF0aCI6Ii82NDE0OTgzNS8zMDM0NjU0MDItODM5NjFiNGUtMDA5Zi00Y2Q1LTkwNWEtMWUzYWZkZmM3YjBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDIxMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYWZlZTVmNDczMmM0MGNiNjhlOTI2MmQyMWQ1NmVhZTc1ZTUxODEzZTM3ZmZkYzdmMjIzMmQ4ZTkyNDcyMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dkjoP_a_rw2ePM85XPI940UknWjLOwPP4HvEyfvzGo4) @kevinginley @mmarsoleta do you have any thoughts of what, how to display a message to users where are there aren't and parent trees linked with a particular orchard?

Also tough about reusing the "missing orchard" error scenario that we already have.
Pretty similar to what Craig created. Just adding a few more instructions on how to recover from the error. 

![image](https://github.com/bcgov/nr-spar/assets/99898407/5b025bf5-b4ca-4f56-a0d7-0590970132f7)
