### ISSUE TITLE
⏫ Create api on oracle to fetch smp mix data

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#848]
Create API to fetch all parent trees SMP Mix values.

### What do to
- Create endpoint `/parent-tree-smp-mix/{orchardId}/{spuId}` under `/api/orchards` `OrchardsEndpoint` on Oracle.
- Create Parent Tree Smp Mix Entity on Oracle.
- Create DTOs to store values
- Fetch all data according to the rule below

⚠  IMPORTANT ⚠ 
This API should be PRETTY MUCH the same one we have for the genetic-quality, but now we need to fetch the SMP Mix, and not the Genetic quallity.

That means you can use the same pattern and flow, just changing the source table to `SEEDLOT_PARENT_TREE_SMP_MIX` instead of `SEEDLOT_PARENT_TREE_GEN_QLTY`.

SQL queries to fetch SMP Mix
```SQL
SELECT * FROM the.ORCHARD o WHERE o.ORCHARD_ID = '405';
SELECT * FROM the.PARENT_TREE_ORCHARD pto WHERE pto.ORCHARD_ID  = '405'; -- 4032, 4169, 4110
SELECT * FROM the.SEEDLOT_PARENT_TREE_SMP_MIX sptsm WHERE sptsm.PARENT_TREE_ID IN (4032, 4169, 4110);
```

**Comment by RMCampos** [comment]
Closing issue as not needed. After discussing and looking at the current implementation, we noticed that all SMP Mix related flows has been made some time ago.

cc: @SLDonnelly @craigyu

**Comment by craigyu** [comment]
Point reduced to 0 as the task was not needed
