### ISSUE TITLE
Status change from submitted to Approved when button is clicked

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#849]
**Describe the task**

When someone with TSC_Admin privileges clicks on the approve button in the seedlot review/approval screen, the status of the seedlot registration needs to change from submitted (SUB) to approved (APP). 

**Acceptance Criteria**
- [ ] status change appears on FE
- [ ] status change appears on BE
- [ ] status change is logged in approval data and user ID in the seedlot reg table in post gres

**Additional context**
This task is reliant on #850

**Comment by mgaseta** [comment]
Already implemented, closing it.
