### ISSUE TITLE
Create Approval Date and User ID/Role in the Seedlot table in post gres

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#850]
**Describe the task**
For logging/auditing and status change purposes, new fields need to be added to the seedlot table in post gres. The fields are:

1. Approval Date `timestamp`
2. Approver User ID `{userName@provider}`

**Acceptance Criteria**
- [ ] fields added to `seedlot` & `seedlot_audit`
- [ ] relevant documentation/data architecture updated

**Comment by RMCampos** [comment]
Required for this task:

- Seedlot history table
- API on Postgres to register approval and user (allowed only for TSC_Admin role users)

**Comment by SLDonnelly** [comment]
@RMCampos above, you mention a seedlot history table. To clarify, is this the same as the seedlot audit table that Marcio created last sprint?

**Comment by craigyu** [comment]
rolled over from sprint 27
