### ISSUE TITLE
STEP 10: API for statuses changes when the TSC Admin clicks approve or disapprove registration

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#852]
**Describe the task**
When the TSC_Admin user clicks the "send back to pending" button, the status needs to change from submitted to pending. This requires an API to be built which will function update the seedlot status and trigger the audit table to record changes.

**Updates after discussions**
Since this change will be quite similar to the approval flow, it was decided that this new API should be able to accept both `approval` and `disapproval` statuses, making sure the Seedlot Audit table get updated with new values.

**Acceptance Criteria**
- [ ] Status change occurs on BE
- [ ] Trigger occurs on Seedlot Audit Table
- [ ] relevant documentation is updated

**Additional context**

This ticket is dependant on #850

**Comment by craigyu** [comment]
rolled over from sprint 27
