### ISSUE TITLE
Spike for #814 - redirect to new spar screen from old

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#854]
**Describe the task**
Need to understand the complexity of redirecting from old spar to new spar. We can also see what is needed to redirect from new spar to old (ie orchard management link/page)

**Acceptance Criteria**
- [ ] document in confluence

Related to task #814

**Comment by craigyu** [comment]
The menu tag implementation can be found here:
`source/ear/src/main/webapp/sparMenuLinks.jsp`

Each menu item is a `jsMenuItem`, which is defined here: `source/ear/src/main/java/ca/bc/gov/mof/spar/web/taglib/MenuItemTag.java`
