### ISSUE TITLE
Development of Seedlot Review Step 3 - Area of Use

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#855]
Describe the task:

Create FE of Seedlot Review, Step 3 (Area of Use) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284868&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/fb3821d6-68df-4f35-8567-39ab3f203530)

Acceptance Criteria

- [ ] Developed as per Figma
- [ ]  relevant documentation updated
- [ ] tested and merged
- [ ] Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added

**Comment by craigyu** [comment]
moved from sprint 28 -> 29

**Comment by RMCampos** [comment]
Rolled over to sprint 30 from 29.

**Comment by craigyu** [comment]
upgrade from 3 to 5
