### ISSUE TITLE
🏆 Development of Seedlot Review Step 9- Audit history

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#856]
Describe the task:

Create FE of Seedlot Review, Step 9 (Audit history) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-285004&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/b4016a5f-b8a4-4b84-b365-a0702a310e9f)

Acceptance Criteria

- [ ]     Developed as per Figma
- [ ]     relevant documentation updated
- [ ]     tested and merged
- [ ]     Develop floater save button place holder - design to be tested by TSC staff

**Additional context**
Dependent on #858 and [#1201](https://github.com/bcgov/nr-spar/issues/1201)

**Comment by mmarsoleta** [comment]
figma link and image added

**Comment by SLDonnelly** [comment]
rolled over from 31 to 32

**Comment by mgaseta** [comment]
Blocked due to missing `approved_timestamp` field.
