### ISSUE TITLE
Development of Seedlot Review Step 4 - Ownership

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#857]
Describe the task:

Create FE of Seedlot Review, Step 4 (Ownership) and integrate endpoints as you go along.

Figma design here: https://www.figma.com/file/ROgZJQezb1DDG4AvEgjtpw/Registration-Process----Reviewer?type=design&node-id=2744-284901&mode=design&t=XxxbormmPMPHmENb-4

![Image](https://github.com/bcgov/nr-spar/assets/99898407/be1b23ab-2179-42c6-b039-506233ecd208)

Acceptance Criteria

- [ ]     Developed as per Figma
- [ ]     relevant documentation updated
- [ ]     tested and merged
- [ ]     Develop floater save button place holder - design to be tested by TSC staff

**Comment by mmarsoleta** [comment]
figma link and image added

**Comment by craigyu** [comment]
moved to sprint 29 from 28
