### ISSUE TITLE
Update Architecture Diagram

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#862]
**Describe the task**

The SPAR architecture diagram needs to be updated before we proceed with a STRA. 
 
The current link is here: https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Architecture

We can use the one from FAM as inspo: **https://apps.nrs.gov.bc.ca/int/confluence/display/FSAST1/Security+Architecture+Diagram**

**Acceptance Criteria**
Create an Architecture View (one combine diagram is common) that shows security impacting concerns such as:

- [ ] The (business) user-classes by privilege/access level (human and non-human), the integrated systems
- [ ]  Physical and virtual topology (include where it is and who “owns” it)
- [ ] Application components and which components are used in the privileged or non-privileged functions
- [ ] The domain objects and the paths/flow of data through the system and what communications channels and networks it uses
- [ ] Show any security controls such as what encryption is used in communication on what channels, where there is authentication, or auditing.

Be sure to indicate any:

- [ ] trust boundaries, entry and exit points (where data moved in and out of the system)
- [ ] where in the system the data is stored – If this is a PWA or things like IndexDB are used make sure to include that.
- [ ] Any segregation between privilege/access levels (network, logical, app, database, etc.)
- [ ] Authentication, Authorization, and Auditing related components.
- [ ] Date, version, page number, title annotations are very much appreciated

**Additional context**

The legacy SPAR security matrix could be used to inform the point regarding privilege/access levels.

**Comment by SLDonnelly** [comment]
Created a Github link too: https://github.com/bcgov/nr-spar/wiki/Architecture

**Comment by RMCampos** [comment]
Architecture diagram. WIP.

![Image](https://github.com/bcgov/nr-spar/assets/2219519/21a94737-117d-481f-b407-a032542e3eab)

**Comment by RMCampos** [comment]
Updated with a bit more of details.

![Image](https://github.com/bcgov/nr-spar/assets/2219519/b7c03e38-d668-453a-a35e-4feab76362ca)
