### ISSUE TITLE
Validate CONSEP QA/Testing: Receive a new seedlot wireframes with TSC QA/Testing team

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#864]
**Acceptance Criteria**
- [ ] Share CONSEP QA/Testing screen wireframes with TSC QA/Testing team
- [ ] Incorporate relevant feedback they may have back into the design

**SME/User Contact**
Victoria Lei

**Comment by SLDonnelly** [comment]
Rolled over from Sprint 26

**Comment by kevinginley** [comment]
We've reviewed the wireframes with TSC staff and the requested revisions can be completed in the next sprint as part of [this new ticket](https://github.com/orgs/bcgov/projects/35/views/23?pane=issue&itemId=58045781)
