### ISSUE TITLE
Create API to fetch lat long and elevation from Oracle

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#874]
Create API to fetch Parent tree:
- latitude_degrees
- latitude_minutes
- latitude_seconds
- longitude_degrees
- longitude_minutes
- longitude_seconds
- elevation

**Comment by RMCampos** [comment]
> curious what we are trying to accomplish here? I would love to move away from decimal degree minutes seconds as an output [@RMCampos](https://github.com/RMCampos)

@webgismd We want to bring the SMP calculations to new SPAR. And based on it works today, we need this information. 

Maybe we can discuss a new data format here? @SLDonnelly 

![Image](https://github.com/bcgov/nr-spar/assets/64149835/b3d79837-ed40-4ad0-9ec0-f5a045d27b33)

Here we have more information, maybe we can chat tomorrow about it: 
- https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/SPR_001A_SMP_CALCULATION+Package+Analysis
  - PROCEDURE recalc (line 792)

**Comment by RMCampos** [comment]
![image](https://github.com/bcgov/nr-spar/assets/2219519/32a42386-a358-4002-99cd-ee5105db607b)

**Comment by webgismd** [comment]
thanks @RMCampos I think this would be a good opportunity to convert these to decimal degrees at least perhaps in the display? and in the new database?.. and to show the conversion as two fields lat/long -- this is just my spatial preference and for usability if folks want to enter these into a device it is sooo much easier as decimal degrees-- 
https://study.com/skill/learn/how-to-convert-degrees-minutes-seconds-to-decimal-degrees-explanation.html 

Step 1: Convert the minutes to degrees by dividing by 60.
Step 2: Convert the seconds to degrees by dividing by 3,600.
Step 3: Find the decimal degree by adding the degrees to the results from steps 1 and 2.

**Comment by SLDonnelly** [comment]
Hello @webgismd and @RMCampos, we will want to maintain the dd, mm, ss format for the time being as changing the format right now will impact reports and other down stream screens. This data will be synced back to the oracle database to be viewed in the seedlot details screens and pulled into canned reports. I'll put a ticket in our backlog for the conversion, but a bit more planning will need to be done on when a good time to switch will be. Does this work for you @webgismd ?

**Comment by RMCampos** [comment]
Morning @webgismd and @SLDonnelly 

Thank you Michelle for providing such detailed information.

Sabina, one tought is that now would be a good time for doing this change actually, since there's only a few records. Only a few changes would be required in the backend (something like a 3 point task, with a migration). And in the frontend would be also easy, less columns to deal with.

As for the reports, we could take the opposite way and making the coversion to dd, mm and ss, if they need.

That's one thought. It's up to you.

**Comment by webgismd** [comment]
good thoughts @RMCampos -- yes the on the fly backs and forwards conversion would support the backs capability of the current down stream formats..
