### ISSUE TITLE
Backend E2E token generation 

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#878]
Get backend tests integrated with our CI workflow aiming to increase security measures and checks for new and existing endpoint APIs.

This ticket will deal with token generation creation and another ticket will deal with the deployment (#1103)

- [ ]Document this procedure in  Confluence

**Comment by craigyu** [comment]
rolled over from sprint 27

**Comment by RMCampos** [comment]
# Context

The backend REST API needs authentication, through a Bearer JWT token that must be sent in the request header. However, FAM doesn't allow any **service authentication** or **service role** that could be used to authenticate an API call. (FAM works with identity providers such as IDIR, Business BCeID and BC Service Card).

**Solution:** create a *fake* token with **jws** (jose library) directly on the test tools in order of having a *valid* token. This sounds simple, but it's not. FAM works with RS256 algorithm, that requires a pair or keys (private and public) in order or **signing**, **validating** and later **decoding** the token. But those also can be generated and handled.

After some hours of work, everything worked! I created a simple and small Node js application.

**GET** token request:
![Image](https://github.com/bcgov/nr-spar/assets/2219519/07239b01-67b1-411a-9bda-6ecaa17b4025)

**POST** token request, validating:
![Image](https://github.com/bcgov/nr-spar/assets/2219519/819e68ed-075e-4a71-b901-43ea293df88f)

**GET** keys request (JWK issuer URI):
![Image](https://github.com/bcgov/nr-spar/assets/2219519/708b91d4-d8cb-4ec6-9622-db1151f803f4)

And finally, working on Swagger API:
![Image](https://github.com/bcgov/nr-spar/assets/2219519/192219de-9dec-41bd-a83d-a5eba5cfca02)

**Comment by RMCampos** [comment]
Key pair of secrets (private + public) in json format: generated here: https://mkjwk.org/

**Comment by RMCampos** [comment]
Roll over to sprint 29.

**Comment by RMCampos** [comment]
Closing this issue as partially finished. The tool for generating and signing JWT was successfully created. This issue will be tracked on #1103
