### ISSUE TITLE
Implement profile management in SPAR backend for Postgres

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#880]
Describe the task:

We need to start planning out and implementing profile management in SPAR. PO will provide rules for Orchard_manager and TSC_Admin profiles.

These rules will need to be implemented on the back-end for Post Gres

Acceptance Criteria:
- [ ] authorization on back end 
- [ ]  roles only see allowed APIs and Endpoints
- [ ] tested and merged
- [ ] relevant documentation updated

**Comment by craigyu** [comment]
rolled over from sprint 28

**Comment by RMCampos** [comment]
Rolled over to sprint 29 from sprint 28.
