### ISSUE TITLE
Analyse CONSEP architecture - Screen assessment

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#886]
**Describe the task**
The goal of this task is to analyse the architecture and organisation of CONSEP pages. Scope is to run an assessment on:
This task focused on the screen assessment

what we will keep
what we will remove
group items together for navigation
review with users to determine if the navigation makes sense

**Acceptance Criteria**
- [ ] Understand user requirements for optimal architecture
- [ ] Document what we will keep and remove
- [ ] Document grouping and navigation options in Figma

**SME/User Contact**
Victoria L.
Eric K.
Bendix H. 
Spencer R.
Marilyn C.
Taylor W.

**Comment by SLDonnelly** [comment]
This ticket is a dependency for review navigation with TSC staff in ticket #887

**Comment by SLDonnelly** [comment]
@PMAKIA1, we have added this UX ticket into Sprint 26 to address a gap in understanding CONSEP page architecture

**Comment by mmarsoleta** [comment]
Roll over from sprint 26 to sprint 27

**Comment by mmarsoleta** [comment]
Broke down "analyse consep architecture" ticket into 3 pieces:

- screen assessment ([https://github.com/bcgov/nr-spar/issues/886]) - will put this one into done.
- organize navigation ([https://github.com/bcgov/nr-spar/issues/958]) - added to sprint 28 backlog
- site map and flowchart ([https://github.com/bcgov/nr-spar/issues/957]) - added to sprint 28 backlog
