### ISSUE TITLE
Review CONSEP architecture with TSC staff

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#887]
Describe the task
The goal of this task is to analyse the architecture and organisation of CONSEP pages and review the proposed navigation to new pages with TSC staff.

This review will higlight:

what we will keep
what we will remove
how we have grouped items together for navigation

The goal of the review will be to determine the navigation makes sense for TSC users.

Acceptance Criteria

    

- [ ] Understand user requirements for optimal architecture
- [ ] Document what we will keep and remove
- [ ] Document grouping and navigation options in Figma
- [ ] Set up a review with TSC staff listed below

SME/User Contact:

Victoria L.
Eric K.
Bendix H.
Spencer R.
Marilyn C.
Taylor W.

**Comment by craigyu** [comment]
rolled over from sprint 27

**Comment by mmarsoleta** [comment]
Rolled over from sprint 28 (haven't started yet)
