### ISSUE TITLE
Design Review: CONSEP QA/Testing: Receive a new seedlot wireframes

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#893]
**Describe the task**
Host a design review of the new seedlot testing wireframes for CONSEP with members from the FDS design team

**Acceptance Criteria**
- [x] Review the purpose of the screens, UX improvements and desired outcomes with FDS design team members. This may be done in a video demo
- [x] Collect and analyse feedback for potential design updates

**Comment by craigyu** [comment]
rolled over from sprint 27
