### ISSUE TITLE
Review CONSEP "Receive a new seedlot wireframes" with TSC Seed Testing staff

### ISSUE THREAD

**Issue by kevinginley** [bcgov/nr-spar#903]
**Describe the task**
Review "receive a new seedlot wireframes" with TSC QA/Seed testing staff for feedback

**Acceptance Criteria**
- [ ] Session to review wireframes with TSC QA/seed testing staff
- [ ] Collect feedback

**SME/User Contact**
Victoria Lei

**Comment by mgaseta** [comment]
Task completed, closing it.
