### ISSUE TITLE
Updates to SMP table and calculation fields

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#905]
**Describe the task**
Design changes needed for step 5. 

1. The Lat, Long and Elevations from the SMP table will be moved to the calculations section on the cone and pollen tab page. See comment here:
https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm?node-id=7151:158019&mode=design#727968608

2. Recalculate button is changed to "calculate"

**Acceptance Criteria**
- [ ] Changes made in FIGMA
- [ ] Changes sent to Craig

**Additional context**
- any additional details that could not be captured above

**Comment by mmarsoleta** [comment]
Reference on figma file: https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7151-158019&mode=design&t=OxLCLovtsoS5UfzG-4

Changes:

**1. Removed second template option and merged with first.**

![Image](https://github.com/bcgov/nr-spar/assets/99898407/d4a41c7c-7697-48bf-bb5f-39b0bb8a5f77)


**2. Step 3 description change.** The description changed to match new button's label. 

![Image](https://github.com/bcgov/nr-spar/assets/99898407/9e4de21e-45ba-4d5a-b471-310a598dae80)


**3. Lat. Long and Elevation columns removed from table.**

![Image](https://github.com/bcgov/nr-spar/assets/99898407/28155557-6331-41d5-a231-4aa35177edd8)


**4. New section title for second tab/table page.** Was genetic worth and effective population size. Now is Genetic worth, effective population size and geospatial data. 

![Image](https://github.com/bcgov/nr-spar/assets/99898407/d8df5abb-f4b6-4f56-82f5-4506db2cda29)


**5. New label for calculate button.** 

![Image](https://github.com/bcgov/nr-spar/assets/99898407/d8df5abb-f4b6-4f56-82f5-4506db2cda29)



**6. New sub-section for "Mean geospatial date"** 

![Image](https://github.com/bcgov/nr-spar/assets/99898407/1e8c4bf0-102f-43e2-ac70-1a4d6490f235)

**Comment by mmarsoleta** [comment]
@SLDonnelly , @craigyu . 

Changes for A-class seedlot registration are done on figma. 
https://www.figma.com/file/xOTQWn4xwyIYGJQPo1OXvm/Registration-process-A-class---New-Version?type=design&node-id=7151-158421&mode=design&t=OxLCLovtsoS5UfzG-4. 

Changes described in the comment above.

**Comment by craigyu** [comment]
@mmarsoleta 
looks good! 

Question:

Are the first 3 checkboxes read-only or functional? (P.T. number and %s)

![image](https://github.com/bcgov/nr-spar/assets/25162561/dbd83e34-2069-4ad8-ae78-28390ce4b8b4)

**Comment by mmarsoleta** [comment]
> @mmarsoleta looks good!
> 
> Question:
> 
> Are the first 3 checkboxes read-only or functional? (P.T. number and %s)
> 
> ![image](https://private-user-images.githubusercontent.com/25162561/313786517-dbd83e34-2069-4ad8-ae78-28390ce4b8b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODQ5MjEsIm5iZiI6MTcxMDc4NDYyMSwicGF0aCI6Ii8yNTE2MjU2MS8zMTM3ODY1MTctZGJkODNlMzQtMjA2OS00YWQ4LWFlNzgtMjgzOTBjZTRiOGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE3NTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWIzODc5OWQ4MDFhZWM2ZGZkYmFhYzA5MTQwMWYwMzY4NjgxM2JlZDgwY2VhMDQyYzQyY2FlNDUyZjEzOGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SIBBchjg-t23U4CF5p5l_n8vib6CoTEqV17vXB1TEWk)

They are read-only.

**Comment by SLDonnelly** [comment]
@mmarsoleta looks good to me thanks Michelly! We can move this to done IMO

**Comment by mmarsoleta** [comment]
> [@mmarsoleta](https://github.com/mmarsoleta) looks good to me thanks Michelly! We can move this to done IMO

Will do, thx!
