### ISSUE TITLE
Document code review process

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#906]
Chris outline the differences between code review and PR review. As we have already to written up or pointed to PR review procedure, we need to now document code review procedure. 

**Additional Context**
Process – Code Review
Purpose / Goal
Examine the application source code and solution for a individual change to ensure that effectively implements the associated requirements and design, is free from functional and non-functional defects, based on the identified risk.  This process focuses on detecting defects and returning the ticket to an upstream process to correct them.
Note: this is a casual code review process not a formal inspection or walk-through.

Inputs
•	Ticket with Elaborated User Story (or Task) for this change.
•	Product documents changed by the Ticket including - Requirements Repository, Architecture, and Design
•	Unit Test Reports (issue – does your process have integration or other tests in a separate workflow or inline with this workflow. If separate, where do they merge into the product)
•	Defect Type Standard
•	Code Review Checklist
Entry
•	The ticket is currently in the Programming Process and: 
o	Programmer considers the programing tasks to be completed.
•	The ticket is returned from an upstream process with remediated defects.
Participants
•	Programmer - Code Author.
•	Programmer - Reviewer. 
Tasks
•	Review changed source code and configurations against the changes in Product/System design specification: 
o	To ensure the changes implement the specified design,
o	Do not introduce any additional functions or features,
o	Source Code matches the documented Product Design changes.
•	Review the source code for each item in the Coding Review Checklist.
•	Execute unit tests and observe all passing.
•	Log non-conformities and return tickets to earliest process applicable to remediation.
Outcome
•	All changes to source code and configuration files, including automated tests implement the requirements and design correctly and completely.
•	All source code quality criteria are met any latent defects in the Product/System Design or Requirements are resolved.
•	No further changes to the Product/System’s source code, configuration, or documentation are needed to meet the goal of the Ticket.
Verification
•	(Exercise – for the way your team works, how will you check that the Code Review was correctly completed)
Exit
The Code Review Process exits when one of the two criteria
•	No Corrections 
o	No quality criteria deficiencies are found, and all checklist items are successful.
•	Corrections required. 
o	Remediation of defects is required such as an unsuccessful checklist item.  Ticket is moved to the earliest process that requires corrections.
Measurement
•	(Some examples – number of defects injected by each upstream process, time to perform the process.)
Guidance
•	Focus on one file and one check list item at a time, complete all checklist items for a file before moving on to the next.  This reduces incomplete reviews confusions in jumping between files.
•	Do not try to correct defects or analyze criteria ambiguity, instead focus on detecting and logging issues to send back to the processes that were responsible for injecting them.
•	When reviewing fixed defects ensure the material was changed to remove the defect rather than a clarification or workaround.  (For example, when fixing a defect in documentation the document should be changed rather than questions and answers in comments)
•	Make sure you have the latest version of the checklists and input materials.
•	Avoid using the same Reviewer repeatedly.  Consider implementing a round-robin reviewer selection help prevent drift in interpretation and assumptions due to repetitive familiarity.
•	If there are defects, log them in the body of the ticket in an “Issues” section at the bottom, move the ticket to the earliest process (Kanban swimlane) that need to do some fixing.  This help support two things (1) performance based earned value, where earned value (%done) is linked to the demonstrated quality and (2) issue and their fixed do not become lone conversations in the comments on a ticket.   
External Resources
•	[https://owasp.org/www-project-code-review-guide/assets/OWASP_Code_Review_Guide_v2.pdf](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fowasp.org%2Fwww-project-code-review-guide%2Fassets%2FOWASP_Code_Review_Guide_v2.pdf&data=05%7C02%7CSabina.Donnelly%40gov.bc.ca%7C1760c33aac804fe408a908dc421b4086%7C6fdb52003d0d4a8ab036d3685e359adc%7C0%7C0%7C638457932155079027%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=uqDXR5Szfi0Tz%2B5oBM7EVSSAZpqaw%2BvnFK3WKuTX2aQ%3D&reserved=0)

**Acceptance Criteria**
- [ ] Code review covers the security concerns that pertain to our project

**Definition of Done**
- [ ] Documented
- [ ] Reviewed by @chris-prince-cgi

**Comment by SLDonnelly** [comment]
Hello @PMAKIA1, I've added this documentation task to sprint 27 to cover ongoing STRA work needed

**Comment by craigyu** [comment]
Added: 

- https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/PR+Test+and+QA+review+strategy

- https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT2/Security+Review+Procedure

Might be a good idea to group these under a page tree, but I couldn't figure out how.

**Comment by RMCampos** [comment]
@craigyu great job putting all this together, BTW! Great work!! I want to take a closer look in the next week. 🚀
