### ISSUE TITLE
Update Architecture Diagram

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#918]
Acceptance Criteria:
DUE Friday March 22nd at 9am

Create an Architecture View (one combine diagram is common) that shows security impacting concerns such as:

- [x] The (business) user-classes by privilege/access level (human and non-human) 
- [x] the integrated systems physical and virtual topology (include where it is and who “owns” it)
- [ ] ~~Application components and which components are used in the privileged or non-privileged functions~~
- [x] The domain objects and the paths/flow of data through the system and what communications channels and networks it uses
- [ ] Show any security controls such as what encryption is used in communication on what channels, where there is authentication, or auditing.

Be sure to indicate any:

- [x] trust boundaries, entry and exit points (where data moved in and out of the system)
- [x] where in the system the data is stored – If this is a PWA or things like IndexDB are used make sure to include that.
- [x] Any segregation between privilege/access levels (network, logical, app, database, etc.)
- [x] Authentication, Authorization, and Auditing related components.
- [ ] Date, version, page number, title annotations are very much appreciated

**Comment by craigyu** [comment]
https://apps.nrs.gov.bc.ca/int/confluence/display/FSADT1/Architecture+Design
