### ISSUE TITLE
User log in/session manage UI usability session

### ISSUE THREAD

**Issue by SLDonnelly** [bcgov/nr-spar#930]
**Describe the task**
After prototypes of the log in/session management UI are completed, usability testing of the new UI needs to be completed

**Acceptance Criteria**
- [ ] usability testing with both SPAR and SILVA users
- [ ] Completed feature in Figma with user feedback incorporated

**SME/User Contact**
- Nanda and Caroline from Team Silva

**Additional context**
- any additional details that could not be captured above

**Comment by mmarsoleta** [comment]
Task refers to creating the navigable prototype to run usability tests with users. 

**Other related tasks are:**

- [#1021](https://github.com/bcgov/nr-spar/issues/1021) 
- [#1022](https://github.com/bcgov/nr-spar/issues/1022) 
- [#1023](https://github.com/bcgov/nr-spar/issues/1023) 
- [#1024](https://github.com/bcgov/nr-spar/issues/1024) 
- [#1025](https://github.com/bcgov/nr-spar/issues/1025) 
- [#1026](https://github.com/bcgov/nr-spar/issues/1026) 
- [#1027](https://github.com/bcgov/nr-spar/issues/1027)
- [#1028](https://github.com/bcgov/nr-spar/issues/1028) 
- [#1029](https://github.com/bcgov/nr-spar/issues/1029)
