### ISSUE TITLE
My Seedlot page cypress test

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#934]
Follow the test plan created in #920 
Create a my seedlot page cypress test. 

**Acceptance Criteria**
- [x] all functionalities are tested on my seedlots page

**Comment by craigyu** [comment]
rolled over sprint 27

**Comment by craigyu** [comment]
After discussion, it is decided that we should test with real data, this will make testing easier down the road, e.g. registration form and review. We will come back to this

**Comment by craigyu** [comment]
Removed from sprint 28

**Comment by ngunner15** [comment]
Added more tests for sorting all the columns.
