### ISSUE TITLE
bug: SonarCloud not reporting anymore

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/nr-spar#937]
SonarCloud appears to have stopped updating quite a while ago.
https://github.com/bcgov/nr-spar/security/code-scanning/tools/SonarCloud/status/configurations/api/f10a68f7b7b9f6560e655004769ba03937bd97048af7f70bea9eba17c4df0cb9

**Comment by craigyu** [comment]
Fixed by Derek alone, closed and updated the sp to 0.
