### ISSUE TITLE
Create labels for backend status

### ISSUE THREAD

**Issue by RMCampos** [bcgov/nr-spar#949]
I've been thinking of adding something like a status corner for the SPAR backends. Something like this (forgive my design skills):

![Image](https://github.com/bcgov/nr-spar/assets/2219519/10f55808-3cc1-44a2-8ec9-d68f70063bf3)

**Comment by SLDonnelly** [comment]
@RMCampos is this ticket covered by the status check that Craig worked on?

**Comment by RMCampos** [comment]
@SLDonnelly sure thing! Closing as completed by Craigs's work on #1529
