### ISSUE TITLE
Oracle api DEV deployment failing inconsistently

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#97]
Success: https://github.com/bcgov/nr-spar/actions/runs/4931422697/jobs/8813438290
Fail: https://github.com/bcgov/nr-spar/actions/runs/4931720417/jobs/8814129572?pr=91 

![image](https://github.com/bcgov/nr-spar/assets/25162561/0ee72954-3cd7-442a-a2bb-489261a33ad3)

**Comment by RMCampos** [comment]
Closing as fixed!
