### ISSUE TITLE
Fill BEC values on seedlot table

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#977]
requires #967 to be done

Once the oracle orchard api is updated, our postgres backend should fill in the BEC values for a seedlot going from pending -> submitted status.

the values to be filled:
- [ ] bgc_zone_code
- [ ] bgc_subzone_code
- [ ] variant
- [ ] bec_version_id

**Comment by SLDonnelly** [comment]
requires BEC API to be developed -> needs to pull from SPAR_BIOGEOCLIMATIC table in oracle.

**Comment by craigyu** [comment]
Rolled over from sprint 29 to 30

**Comment by craigyu** [comment]
point went down from 3 to 2
