### ISSUE TITLE
⏫ Fill in geospatial values on seedlot table

### ISSUE THREAD

**Issue by craigyu** [bcgov/nr-spar#979]
Requires:
- [x] #965

We need to fill in these geospatial data when a seedlot status goes from pending -> submitted:
- [ ] latitude_degrees*
- [ ] latitude_minutes*
- [ ] latitude_seconds* 
- [ ] longitude_degrees*
- [ ] longitude_minutes*
- [ ] longitude_seconds*
- [ ] elevation*

* values are the mean value of the seedlot parent trees, excluding values from SMP mix data

**Comment by SLDonnelly** [comment]
need to fill in post GIS geompoint as well
